### ISSUE TITLE
Scanner: no support for external DB

### ISSUE THREAD

**Issue by hairmare** [stackrox/stackrox#10134]
We are currently deploying Stackrox using the Helm chart and are trying  to switch to using `db.external=true` to use a DBaaS PostgreSQL. This works well for the central services pod, but the scanner still deploys it's own database from [here](https://github.com/stackrox/helm-charts/blob/80c9b8e6257d1fd467a261e154bb07cfbd551f99/4.3.4/central-services/templates/02-scanner-06-deployment.yaml#L153-L294).

## Expected Outcome

The scanner connects to the configured external database

## Observed Outcome

The scanner deploys it's own database Deployment and uses that instead of keeping it's data in the external database.

## Further information

We currently can't deploy a production grade Stackrox installation using the provided Helm charts as the database that gets deployed for the scanner is nowhere near production grade.

We believe that our requirements would be met if the chart allowed deploying the scanner with an external DB. If the scanner needs to have an in-cluster database, then it would be nice if there were some additional flags that make it tunable into a production grade deployment (eg. by enforcing TLS connections and running a clustered PostgreSQL).

**Comment by Maddosaurus** [comment]
Hi @hairmare and thanks for the report!
We're currently undergoing bigger changes to the Scanner deployment, so this is subject to change.
I have pinged the Scanner team and asked whether they have plans to support external DBs with the new setup.
We'll update this issue accordingly. Thank you for the patience!

**Comment by hairmare** [comment]
Hey @Maddosaurus 

Thanks for the quick update! That is much appreciated.

I ended up realizing that it's an ephemeral database and that the provided Istio rules cover the production requirements i was asking for.

I'm going to go ahead and close this issue since my initial request is moot. Please apologize to the Scanner team if i generated unnecessary noise. 

I'll create a new issue down the road once i have a concrete story about any requirements that arise in non Istio cases.
