### ISSUE TITLE
Revamp Database Migration and Management Process

### ISSUE THREAD

**Issue by rfizzle** [stackrox/stackrox#10141]
The way Stackrox manages, drops, recreates and copies databases is really a bad implementation. I've had weird DB permission issues that end up blowing away my Stackrox databases. Woke up this morning to one of my datacenter instances empty when trying to patch central and scanner TLS certs, not even a version upgrade. I highly recommend completing redesigning the way this is done.

Migrations should be explicit, not implicit, when running the central services, best as a separate process and not invoked on normal service startup, and at no point should tables be dropped.

**Comment by Maddosaurus** [comment]
Hi @rfizzle and thanks for opening discussion on this!
It is concerning what you describe, so we would be interested to hear some more details about your environment and the circumstances that this happened.
As a start, could you tell us which version of StackRox you are running and what Kubernetes distro/version you are using?
I would also be interested to hear whether you are using your own DB or the one provided by StackRox.
Is there any kind of automation you are using to manage the configuration of our platform, e.g. an Operator, Argo, or Scripts?
Feel free to include as much information as you can share additionally. 

So far, we have received no reports outlining what happened to you, so we would like to dig deeper into this and investigate!
Moreso, as a complete redesign would mean a significant time investment that we really need to sell to our Product Managers well :smile: For that, we need compelling evidence that the current design needs improvements.
Thanks for your help!

**Comment by rfizzle** [comment]
I was running version 3.74.0. I have a managed database (Postgres) that is bootstrapped via my DBOps team. Basically as part of their automation, their DB user ends up applying ownership of all of the databases. The user I have for Stackrox is not an admin, and only has DB_CREATE permission in Postgres, so it can only drop the databases it owns. I've had instances where when Stackrox loses ownership of one of the four databases, is unable to drop (not sure which one) and for whatever reason during the database migration process, loses everything. To replicate, you'd probably have to play with the ownership of the various databases before a migration. I'm guessing the pivot to an "external database" was to promote more managed database instances. I've had to restore from backups and at this point will likely move away from my teams managed database to just an unmanaged Postgres pod running along side the deployment.

**Comment by dashrews78** [comment]
@rfizzle To be clear, you were running 3.74.0 in Postgres mode?  Were you performing an upgrade?

Postgres itself was not supported until 4.0.0.  Initially we performed migrations with database copies and as such required the database user to have admin permissions.  Without those permissions, any migrations prior to 4.1 are unlikely to be stable.  We updated the migrations in 4.1 to be much more permission friendly, (i.e. we only use one database for external).  But that applies to 4.1 forward.  An upgrade from 3.74 to 4.1 would likely still encounter the issues you are hitting.   

How does stackrox lose ownership to the databases it creates?  That sounds like an issue outside of stackrox, from what I can tell.

I think the simplest path would be to negotiate with the DB guys to give the stackrox use admin privileges, so you can upgrade to 4.1 or greater (preferably 4.3).  After that upgrade is complete they can reduce the permissions on the user as stackrox would no longer need permissions to create a database.

**Comment by rfizzle** [comment]
Ok, that makes more sense. I went ahead and just deployed a Postgres container alongside Stackrox in the `stackrox` namespace and will run it as is. I have everything configured via a terraform provider, and the data is exported anyway, so I'm not too concerned with statefulness. If the newer versions no longer copy databases around and such, then I believe this should resolve this issue. Appreciate the help.
