### ISSUE TITLE
StackRox central 4.4.0 is trying to write to deprecated/'no longer needed' stackrox-db volume

### ISSUE THREAD

**Issue by danekantner** [stackrox/stackrox#10542]
StackRox central 4.4.0 is trying to write to deprecated/removable stackrox-db volume in the move-to-current process that runs at startup.

Stackrox Central 4.4.0 is crashing after an earlier restart of all Central services. It is trying to create a folder `/var/lib/stackrox/.db-init` but this is the folder corresponding to the `stackrox-db` volumeMount that was marked as deprecated and 'no longer needed' in the StackRox 4.1 Release Notes. The migration to central-db stand-alone SQL container had already taken place.

The [release notes for StackRox 4.1](https://docs.openshift.com/acs/4.1/release_notes/41-release-notes.html#notable-technical-changes_release-notes-41) read: `The Central persistent volume claim (PVC) stackrox-db is deprecated and is no longer needed after this upgrade.`. The notes for 4.2 go in to further detail on setting an annotation for the Operator to remove the PVC itself.

It seems, based off of this log, that this is not the case and it is in fact needed in some capacity? Is there a flag that can be set somewhere else that prevents the database migration from taking place? 
The annotation `  platform.stackrox.io/obsolete-central-pvc: "true"` has been added now as well and the deployment rolled but that did not change that it is trying to run this still.

central log:
```
move-to-current: 2024/03/26 21:15:10.472841 logger.go:61: Info: Move databases to current
move-to-current: 2024/03/26 21:15:10.472922 logger.go:61: Info: mkdir: cannot create directory '/var/lib/stackrox/.db-init': Read-only file system
```

https://github.com/stackrox/stackrox/blob/b276ac4c5d8f47f91d9b187d7604d0665225e07b/image/rhel/static-bin/start-central.sh#L9

move-to-current assumes if the folder doesn't exist as a symbolic link it should run the move -- the container is read only otherwise though so there's no way the link could exist if the stackrox-db pvc were removed. https://github.com/stackrox/stackrox/blob/b31dc5c671ffee35fda083aa2830cda51d2c9b1b/image/rhel/static-bin/move-to-current#L13

**Comment by danekantner** [comment]
I was able to work around this by creating the directory in the Dockerfile myself so the move-to-current just skips the migration -- adding the `stackrox-db` pvc back may have fixed it, not clear, I read the code and didn't want to risk it running the migrate on an empty folder so I just made it just skip it. 

work-around added to my Dockerfile for main:
```
 RUN mkdir -p "/var/lib/stackrox/.db-init" && \
     chown -R 4000:4000 "/var/lib/stackrox/.db-init" && \
     ln -s "/var/lib/stackrox/.db-init" "/var/lib/stackrox/current" && \
     chown -h 4000:4000 "/var/lib/stackrox/current"
```

**Comment by c-du** [comment]
@danekantner Thank you for providing the feedback. 
We have not fully removed stackrox-db PVC from the system yet to support customer upgrading from earlier versions. If the user is ready to deprecate it, they can do so by following the instructions such as with the annotation. 

Can you please provide some more details including:
1. How did you install the instance? Do you upgrade it from some earlier versions?
2. Can you provide the command of 'oc describe deploy central'?

**Comment by danekantner** [comment]
1) This is all generated from the roxctl kubernetes manifests (not openshift, not helm, but just standard kubectl manifests)
2) This has been upgraded pretty much every 4.x release that has been out. The move to the new central-db took place _months ago_ and I removed the references to the `stackrox-db` volume mount when migrating from 4.2.2 to 4.3.1, three releases ago now. There is zero reason this should be trying to run now as far as I can tell and it's against the documented release notes from prior releases. 

My full migration path has been 3.74.0 -> 4.0 -> 4.2.0 -> 4.2.2 -> (stackrox-db volume mount removed) 4.3.1 -> 4.3.4 -> 4.4.0

**Comment by c-du** [comment]
Please check this doc:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_security_for_kubernetes/4.2/html-single/upgrading/index#remove-central-attached-pv-overview_upgrade-roxctl
Please note that we replace the stackrox-db to emptyDir instead of removing it.

```
   volumes:
      …
      - name: stackrox-db
        emptyDir: {}
```

**Comment by msugakov** [comment]
Hi @danekantner 

Are you ok if we close this issue or do you have any pending questions that still need answers?

Thanks,
Misha

**Comment by danekantner** [comment]
Thank you this can be closed
