### ISSUE TITLE
add integration with harbor

### ISSUE THREAD

**Issue by Nello-Angelo** [stackrox/stackrox#10891]
add integration with harbor

**Comment by JoukoVirtanen** [comment]
Can you be more specific? How would you like Harbor to be integrated into ACS?

**Comment by Nello-Angelo** [comment]
<img width="1388" alt="Screenshot at Apr 26 14-02-41" src="https://github.com/stackrox/stackrox/assets/82488489/24e6bf67-de68-4a84-a8b1-30d38b06399d">

like these repositories

**Comment by RTann** [comment]
We do not have any plans to add an explicit Harbor integration at this time. We encourage the community to consider adding this integration, if desired :)

I will close this as a duplicate of https://github.com/stackrox/stackrox/issues/8854
