### ISSUE TITLE
Support multiple Versions of CIS-Benchmark

### ISSUE THREAD

**Issue by Jeansen** [stackrox/stackrox#12062]
I've installed version 4.4 of Stackrox. It supports CIS-Benchmark 1.5 only. The most recent   version is 1.9.0. Also, depending on the Cloud provider, there are different versions of this Benchmark (Kubernetes, AWS, GKE, etc ...) and finally these Benchmarks are valid for different versions of Kubernetes. Usually for a range of three versions, e.g. Kubernetes 1.27 to 1.29.

**Comment by Maddosaurus** [comment]
Hi @Jeansen and thanks for opening discussion on this!
We have an ongoing effort to rework bigger parts of our compliance reporting that will change how and what benchmarks we are handling.
I cannot speak to timelines for when this is planned to release, though. The effort will likely continue beyond 4.6, with continuous improvements every release!
Hope that helps!

**Comment by Maddosaurus** [comment]
I've closed the issue for now. Keep an eye out on changelogs referencing `Compliance`, which is the component responsible for benchmark reporting. Example from the current changelog:
https://docs.openshift.com/acs/4.5/release_notes/45-release-notes.html#compliance-updates_release-notes-45

Feel free to reopen the issue if there are additional questions!
