### ISSUE TITLE
Installing stackrox-central-services on OpenShift via ArgoCD: admin password not working

### ISSUE THREAD

**Issue by kastl-ars** [stackrox/stackrox#12125]
Hi,

I am trying to deploy StackRox (not ACS) onto a OpenShift cluster via ArgoCD.

I found that the admin password is not respected, neither when using it as plaintext `values` (which comes from a Vault instance, it is not in cleartext in the GitOps git repository) nor when using the `httpasswd` key with a htpasswd bcrypt hash.

This means that the `roxctl` command to create the init-bundle fails to authenticate. And the web UI also does not work using the admin password.

I also noticed that the sync does not work properly (maybe due to the out-of-sync issues in #12124). But also, secrets went missing and were not being recreated during syncs.

Is there some magic in the helm chart that does not work when using ArgoCD (which AFAIK just uses a `helm template` under the hood and then applies the manifests to Kubernetes instead of using `helm install` directly)?

I found nothing interesting in the central pod's logs, so my question is where I could start looking? Increase the loglevel? More debugging output?

Any roxctl commands that I could run in the pod (that do not require the password, as that does not work).

Thanks in advance!

Johannes

**Comment by kastl-ars** [comment]
> I also noticed that the sync does not work properly (maybe due to the out-of-sync issues in https://github.com/stackrox/stackrox/issues/12124). But also, secrets went missing and were not being recreated during syncs.

This seems related to #8520  and #2482, but does not explain why the admin password is not working.

**Comment by mtodor** [comment]
Hi @kastl-ars! 

I'm not sure how ArgoCD handles sensitive data. With helm install/update, you can set `central.adminPassword.value`. It has to be a plain text.

Please check the description in the example values file: [values-private.yaml.example](https://github.com/stackrox/helm-charts/blob/17390a0cc43a86e2b171b7b7328006afa135768a/4.5.0/central-services/values-private.yaml.example#L110)

There is also an option to generate a password. In that case, you have to fetch it from the cluster first before using `roxctl`. Generated values should be stored in a secret: [99-generated-values-secret.yaml](https://github.com/stackrox/helm-charts/blob/17390a0cc43a86e2b171b7b7328006afa135768a/4.5.0/central-services/templates/99-generated-values-secret.yaml#L18)

**Comment by kastl-ars** [comment]
Thanks for the reply @mtodor!

I think we can set this on hold until the other issues regarding ArgoCD sync (#12124 and https://github.com/stackrox/stackrox/issues/2482#issuecomment-2249727577) are solved.

Once the sync has finished successfully I can try and debug, why the admin password does not work.

(As stated in the inital description, I tried both setting the `value` and the `htpasswd`. To avoid having sensitive values in Git the value was pulled in from Hashicorp Vault, but that detail should not matter).

**Comment by mclasmeier** [comment]
Could you try with the 4.5.0 Helm chart and report back?
Moritz

**Comment by kastl-ars** [comment]
I will tackle this after the PVC issue was solved https://github.com/stackrox/stackrox/issues/2482#issuecomment-2249727577), as it might be causing the sync to fail...

**Comment by kastl-ars** [comment]
After solving the PVC issue by manually creating the PVC and using an existing claim, the admin password being set in the values.yaml suddenly is being respected.

So I think that this issue was a non-issue caused by the ArgoCD sync being broken due to the PVC issues...
