### ISSUE TITLE
Stackrox vulnerability reports are being sent at 2 AM

### ISSUE THREAD

**Issue by imdmahajankanika** [stackrox/stackrox#12411]
Hello,

How to customise the timings for sending Stackrox vulnerability reports?

**Comment by msugakov** [comment]
Hi @imdmahajankanika 

Colleagues shared info that it is not unfortunately possible to set a time of day for the VM reports to go out. Central starts processing them when server time rolls over to the date or day of week that they are set to run. Report-processing is a long-running task, and the reports get emailed once that task completes.

We'd consider a community [contribution](https://github.com/stackrox/stackrox/blob/master/.github/contributing.md) for making this setting configurable.

I'll close this issue but please feel free to add comments and/or report a new one should you have further questions.
