### ISSUE TITLE
StackRox Collector Not Starting on ARM64 Nodes - Need Help with ARM64 Support

### ISSUE THREAD

**Issue by SitoRBJ** [stackrox/stackrox#12520]
Hello everyone,

I've noticed that the official StackRox collector image repository doesn't have recent versions (v4.4 or v4.5) that explicitly state support for ARM64 architectures.

In my cluster, I have nodes running both AMD64 and ARM64 architectures. Unfortunately, the collector fails to start on the ARM64 machines, and I would like to use a more recent version of the collector (I see the latest arm available is 3.19).

I'm deploying via the official StackRox Helm Chart, but I'm unsure how to resolve this issue, and I might be overlooking something.

Any advice or guidance would be greatly appreciated. 

Thanks in advance for your help!

**Comment by Molter73** [comment]
Hi @SitoRBJ,

First off and just in the sake of clarity, we don't officially support Arm64, collector images for this architecture are built as a best effort but no official support is provided for them (yet).

That said, there's one other thing to clarify and that is that collector uses its own separate versioning from stackrox, you can see in [this file](https://github.com/stackrox/collector/blob/master/RELEASED_VERSIONS) that collector 3.19 corresponds with stackrox 4.5, so you should be good to use that image.

One last thing I'll look into, we retag collector to match with the versions for stackrox, but it seems something is not quite right, only the amd64 image is being retagged, I'll post an update here once I have a bit more context.

**Comment by SitoRBJ** [comment]
@Molter73 Thank you very much for getting back to me so quickly, everything has been clarified.

Now I only have a doubt, are there multi-arch images of versions 3.19 or 3.18? to know if I can reference this image in my Helm Chart so the collector can be created independently of the architecture of the node that is created.

Thank you very much again for your attention

**Comment by Molter73** [comment]
@SitoRBJ, there are, the `3.19.0` tag is a manifest for all supported archs, so using that should make it so your nodes resolve to the correct arch. Same for the 3.18 versions in the file I shared previously, just replace the stackrox version in the collector image to the 3.18/3.19 you want to use.

**Comment by SitoRBJ** [comment]
I am really grateful to you @Molter73 . I hope you have a good week

**Comment by SitoRBJ** [comment]
Hello @Molter73, the change has gone well for the arm nodes but the collectors do not lift on the amd nodes. This is the error shown in the pod logs:

```bash
Defaulted container "collector" out of: collector, compliance
exec /bootstrap.sh: exec format error
```

Image used: 3.19.1-slim

**Comment by Molter73** [comment]
That's weird, that is the message you would get from running an image for a wrong architecture 🤔
 
Would you mind sharing the exact steps you used for updating the image? I don't have much experience on clusters with mixed architectures, but I'd assume using a manifest like the one you are using should auto-resolve the architecture.

**Comment by SitoRBJ** [comment]
Hello @Molter73,

Just update the version of the chart.

Run the `helm update` command.

I added this section to my values.yaml, because before I was creating images with the v4.4 tag for collector that didn't work on ARM.

```yam
  image:
    collector:
      tag: 3.19.1
```

All other components are upgraded to v4.5.1. This is part of the configuration we had of the collector, maybe there is something obsolete

```yaml
  collector:
    exposeMonitoring: true
    collectionMethod: EBPF
    disableTaintTolerations: false
    slimMode: true
```

Thank you for your help and patience

**Comment by Molter73** [comment]
That's weird, the configuration looks good to me. Have you tried `kubectl inspect ds/collector` to see the configuration has been properly applied and whether there are any events that point to what the actual image being used is? To me it looks like your cluster is trying to use the Arm image on amd nodes, but have no idea why that would happen.

Alternatively, you could try setting `slimMode` to false, the latest version of collector no longer makes any distinction on this, but the registry being used can change. I think it should have no effect, but it's worth the try IMO.

**Comment by SitoRBJ** [comment]
Thank you very much @Molter73, by upgrading to standard images and disabling the slim option everything worked perfectly. Thank you very much for your attention and help.

**Comment by Molter73** [comment]
@SitoRBJ sounds like your issue has been resolved, so I'm closing this one. If that's not the case, feel free to re-open the issue.

If you have any other questions or follow-ups, feel free to open another issue.
