### ISSUE TITLE
Update README instructions for Manual Installation using Helm section

### ISSUE THREAD

**Issue by adelca** [stackrox/stackrox#12721]
Hi, I followed the instructions and I got this error:

```
Error: execution error at (stackrox-central-services/templates/NOTES.txt:1:10):

FATAL ERROR:
Starting from 4.1, we stop creating central PVC during installation. Databases and
persistent data are stored in Central DB or external databases. You may use `--set
central.persistence.none=true` during Helm install to override default persistence config. Got
map[hostPath:<nil> none:<nil> persistentVolumeClaim:map[claimName:<nil> createClaim:<nil> size:<nil>
storageClass:<nil> volume:map[volumeSpec:<nil>]]]
```

Now, this is briefly mentioned in this other README: https://github.com/stackrox/helm-charts/blob/main/4.5.1/central-services/README.md

Also, it would be good to add instructions on what is needed for persistent data, that comment says it will be done on a central DB pod or external DB, what happens if I also use central.persistence.none=false? What is used central.persistence variables for? and how is it different to central DB persistent storage model?

**Comment by c-du** [comment]
Which document did you follow in the first try?

**Comment by adelca** [comment]
> Which document did you follow in the first try?

The one belonging to the project I created this issue for: https://github.com/stackrox/stackrox/blob/master/README.md
This section:
https://github.com/stackrox/stackrox/blob/master/README.md#default-central-installation

**Comment by msugakov** [comment]
Hi @adelca 

Thanks for reporting! There's https://github.com/stackrox/stackrox/pull/12943 to address this issue.

**Comment by sachaudh** [comment]
Thanks, @msugakov! Once that PR is in, would you mind closing this issue?

**Comment by SimonBaeumer** [comment]
Merged in https://github.com/stackrox/stackrox/pull/12943
