### ISSUE TITLE
Additional Compliance Controls

### ISSUE THREAD

**Issue by jseiser** [stackrox/stackrox#12763]
Im not sure if this is something that can be sourced from the community or not, but it would be ideal to be able to load in the CIS 1.5 Compliance requirements, or the DISA Kubernetes stig.  

Whats currently there checks for a lot of control thats EKS just doesnt provide.

**Comment by Maddosaurus** [comment]
Hi @jseiser,
thanks for pitching this idea!
We're currently redesigning the Compliance part of StackRox, which will result in a more modular architecture that allows for an easier addition of compliance controls.
I cannot give you an expected delivery date right now, but I can tell you that we are actively working on this.
I'll be closing the issue for the moment, but please feel free to reopen if you have any questions!
