### ISSUE TITLE
The absence of collector-ebpf files in sensor images

### ISSUE THREAD

**Issue by TrueBad0ur** [stackrox/stackrox#12885]
Hi, I'm trying to setup **stackrox-central-services** and **stackrox-secured-cluster-services** afterwards via helm charts
```
stackrox-central-services version - 4.5.2
stackrox-secured-cluster-services version - 4.5.2
```
With the main helm I don't have any problems but when I'm trying to install **secured** one (as it's described in the manual) I get a common error at first:
```bash
Attempting to download collector-ebpf-5.4.0-165-generic.o
Attempting to download kernel object from https://sensor.stackrox.svc:443/kernel-objects/2.10.0/collector-ebpf-5.4.0-165-generic.o.gz
HTTP Request failed with error code 404
```

As I've found the problem is described in these links - [link1](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.1/html/troubleshooting_collector/commonly-occurring-error-conditions#unavailability-of-the-kernel-driver_error-conditions) and [link2](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.1/html/troubleshooting_collector/commonly-occurring-error-conditions#unavailability-of-the-kernel-driver_error-conditions)

I've checked all the steps:
1. I have this driver on my nodes
2. The kernel version on nodes is the one from [this ](https://github.com/stackrox/collector/blob/master/kernel-modules/KERNEL_VERSIONS) list

Looks like this description is for 4.1 version, and in the current version the drivers aren't included into the sensor images, so obviously I get 404
As it's described in the [current release notes](https://docs.openshift.com/acs/4.5/release_notes/45-release-notes.html):
> The rhacs-collector* and rhacs-collector-slim* images have been deprecated. They are now functionally same and do not include kernel drivers

> Kernel support packages and driver download functionality are deprecated.

So this raises the following question - how for now should this situation be solved? The collector pod still tries to download it
Maybe I'm wrong and it's described somewhere in the manuals, but I didn't find the new conception description anywhere

Thanks

**Comment by Molter73** [comment]
Hi @TrueBad0ur,

4.4 is the last version that used downloadable drivers, the code for downloading the drivers was unfortunately left in 4.5 but the drivers are not built anymore. 4.6 will remove the downloading mechanism altogether.

Could you share the full log from collector? From the kernel version that its trying to download I think the problem is the newer driver is not compatible with your kernel and its trying to fallback to the old method.



> As it's described in the [current release notes](https://docs.openshift.com/acs/4.5/release_notes/45-release-notes.html):
> 
> > The rhacs-collector* and rhacs-collector-slim* images have been deprecated. They are now functionally same and do not include kernel drivers
> 
> > Kernel support packages and driver download functionality are deprecated.

As a sort of answer to this, from the same [release notes](https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/4.5/html/release_notes/release-notes-45#removed-features_release-notes-45):
> EBPF collection has been removed. Configurations are automatically converted to CORE_BPF when you upgrade, and the forceCollection option is no longer applicable.

**Comment by TrueBad0ur** [comment]
Thanks for your answer
The full log looks like this:

`❯ k -n stackrox logs ds/collector -c collector`
```bash
context  02:30:02 PM
Found 6 pods, using pod/collector-pxxx5
Collector Version: 3.19.2
OS: Ubuntu 20.04.6 LTS
Kernel Version: 5.4.0-165-generic
Starting StackRox Collector...
[INFO    2024/10/03 11:28:00] Hostname: 'cl1ddtapb9ffb318bmu1-okur'
[INFO    2024/10/03 11:28:00] User configured collection-method=ebpf
[INFO    2024/10/03 11:28:00] Ignore network : 169.254.0.0/16
[INFO    2024/10/03 11:28:00] Ignore network : fe80::/10
[INFO    2024/10/03 11:28:00] Afterglow is enabled
[INFO    2024/10/03 11:28:00] BPF RingBuffer map type is not available (errno=Invalid argument)
[INFO    2024/10/03 11:28:00] Sensor configured at address: sensor.stackrox.svc:443
[INFO    2024/10/03 11:28:00] Attempting to connect to Sensor
[INFO    2024/10/03 11:28:03] Successfully connected to Sensor.
[INFO    2024/10/03 11:28:03] Module version: 2.10.0
[INFO    2024/10/03 11:28:03] Config: collection_method:ebpf, scrape_interval:30, turn_off_scrape:0, hostname:cl1ddtapb9ffb318bmu1-okur, processesListeningOnPorts:1, logLevel:INFO, set_import_users:0, collect_connection_status:1, enable_detailed_metrics:1, enable_external_ips:0
[INFO    2024/10/03 11:28:03] Candidate drivers:
[INFO    2024/10/03 11:28:03] collector-ebpf-5.4.0-165-generic.o
[INFO    2024/10/03 11:28:03] Attempting to download collector-ebpf-5.4.0-165-generic.o
[INFO    2024/10/03 11:28:03] Attempting to download kernel object from https://sensor.stackrox.svc:443/kernel-objects/2.10.0/collector-ebpf-5.4.0-165-generic.o.gz
[INFO    2024/10/03 11:28:03] HTTP Request failed with error code 40
```

Images used:
- quay.io/stackrox-io/collector-slim:4.5.2
- quay.io/stackrox-io/main:4.5.2

So yeah, looks like it falls back to the old method for some reason
Which versions of driver and kernel are compatible to each other, so I'd be able to test?
Seems like the kernel version is compatible - [link](https://github.com/stackrox/collector/blob/master/kernel-modules/KERNEL_VERSIONS#L6541)

**Comment by Molter73** [comment]
For that kernel, you'll need to use collector version 4.4, latest patch release is 4.4.5 I believe. If you can upgrade the kernel to something like 5.8+ you should be able to use the new driver, we regularly run tests on Ubuntu 20.04 hosted on GCP and those work correctly.

**Comment by TrueBad0ur** [comment]
Looks like the problem was in the exception of ring_buffer map in the kernel on the 5.4 version
Because as I found out it was introduced in 5.8
Set it up with clean 5.8+ kernel, everything is okay
Thanks so much ^_^
