### ISSUE TITLE
Sensor can not connect to Central 

### ISSUE THREAD

**Issue by ThuanLee** [stackrox/stackrox#13421]
I have tried to create Secured Cluster in different cluster to Central. After Sensor start up, a error occurs. I guest this error relates to  grpc message size. Thank you for helping me. Below is error's detail:

```
kubernetes/listener: 2024/11/25 11:25:40.456340 resource_event_handler.go:147: Info: Initializing "clusteroperators" informer
kubernetes/listener: 2024/11/25 11:25:40.456426 listener_impl.go:107: Warn: Resource "imagedigestmirrorsets" does not exist...
kubernetes/listener: 2024/11/25 11:25:40.456471 listener_impl.go:107: Warn: Resource "imagetagmirrorsets" does not exist...
kubernetes/listener: 2024/11/25 11:25:40.457518 resource_event_handler.go:173: Info: Initializing "imagecontentsourcepolicies" informer
common/config: 2024/11/25 11:25:40.464062 handler.go:87: Info: Received configuration from Central: {
  "config": {
    "admissionControllerConfig": {
      "enabled": true,
      "timeoutSeconds": 10,
      "scanInline": false,
      "disableBypass": false,
      "enforceOnUpdates": true
    },
    "registryOverride": "",
    "disableAuditLogs": true
  }
}
common/config: 2024/11/25 11:25:40.464106 handler.go:96: Info: Stopping audit log collection
common/sensor: 2024/11/25 11:25:40.573591 central_communication_impl.go:167: Info: Established connection to Central.
common/sensor: 2024/11/25 11:25:40.573649 central_communication_impl.go:176: Info: Communication with central started.
common/delegatedregistry: 2024/11/25 11:25:40.596170 delegated_registry_handler.go:170: Info: Received 9 updated and 0 deleted image integrations
common/config: 2024/11/25 11:25:41.119275 handler.go:76: Info: Received audit log sync state from Central: {
  "nodeAuditLogFileStates": {
  }
}
common/sensor: 2024/11/25 11:25:41.367803 central_receiver_impl.go:58: Info: Stopping with error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4638032 vs. 4194304)
common/sensor: 2024/11/25 11:25:41.367898 central_communication_impl.go:181: Info: Communication with central ended.
common/sensor: 2024/11/25 11:25:41.367956 sensor.go:386: Info: Communication with Central stopped. Retrying.
common/sensor: 2024/11/25 11:25:41.367969 central_sender_impl.go:113: Info: Error on sending to stream: EOF
common/sensor: 2024/11/25 11:25:41.367983 sensor.go:333: Info: Updating Sensor State to: offline-mode
kubernetes/eventpipeline: 2024/11/25 11:25:41.368022 pipeline_impl.go:125: Info: Component runs now in Offline mode
common/networkflow/manager: 2024/11/25 11:25:41.368111 manager_impl.go:268: Info: Component runs now in Offline mode
common/signal: 2024/11/25 11:25:41.368138 signal_service.go:54: Info: Component runs now in Offline mode
common/processsignal: 2024/11/25 11:25:41.368148 pipeline.go:91: Info: Component runs now in Offline mode
common/admissioncontroller: 2024/11/25 11:25:41.368162 alert_handler.go:41: Info: Component runs now in Offline mode
common/compliance: 2024/11/25 11:25:41.368174 auditlog_manager_impl.go:55: Info: Component runs now in Offline mode
common/image: 2024/11/25 11:25:41.368193 service_impl.go:137: Info: Component runs now in Offline mode
common/compliance: 2024/11/25 11:25:41.368210 node_inventory_handler_impl.go:79: Info: Component runs now in Offline mode
common/sensor: 2024/11/25 11:25:41.368219 notifiable.go:26: Info: Component 'Kernel probe server handler' runs now in Offline mode
common/sensor: 2024/11/25 11:25:41.368229 notifiable.go:26: Info: Component 'Kernel object cache' runs now in Offline mode
common/scannerdefinitions: 2024/11/25 11:25:41.368249 http_handler.go:47: Info: Component 'Scanner definitions handler' runs now in Offline mode
common/sensor: 2024/11/25 11:25:41.368268 sensor.go:403: Info: Central communication stopped: communication stopped. Retrying after 8s...
```

**Comment by vikin91** [comment]
Hi @ThuanLee , thanks for reporting! 
Could you please share the versions of Sensor and Central?
It would be also good to look at the full diagnostic bundle.

**Comment by ThuanLee** [comment]
Sensor version is 4.2, Central version is 4.5
Here is full diagnostic bundle

[sensor.log](https://github.com/user-attachments/files/17911766/sensor.log)

**Comment by vikin91** [comment]
Thank you! This confirms my suspicion that Sensor is very old. Sensors 4.1 and 4.2 were known to be affected by 
```
Info: Stopping with error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4638032 vs. 4194304)
```

We do not treat that as a bug, simply the payload of external network information (information about which IP CIDRs belong to which cloud company) got bigger than the max payload limit configured for Sensor and Central. I think, that starting from  version 4.3 the components implement an automatic discovery of the message size and dynamically reconfigure the gRPC connection, so it would be the first version that should be free from this problem. However, I would suggest to always use Sensor in the same version as Central to avoid other potential problems.

Would it be possible that you upgrade Sensor to 4.5?

**Comment by ThuanLee** [comment]
> Thank you! This confirms my suspicion that Sensor is very old. Sensors 4.1 and 4.2 were known to be affected by
> 
> ```
> Info: Stopping with error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4638032 vs. 4194304)
> ```
> 
> We do not treat that as a bug, simply the payload of external network information (information about which IP CIDRs belong to which cloud company) got bigger than the max payload limit configured for Sensor and Central. I think, that starting from version 4.3 the components implement an automatic discovery of the message size and dynamically reconfigure the gRPC connection, so it would be the first version that should be free from this problem. However, I would suggest to always use Sensor in the same version as Central to avoid other potential problems.
> 
> Would it be possible that you upgrade Sensor to 4.5?

I think it is not possible. I have installed Secured Cluster by using the Operator, but Operator version is depend on Cluster version. It  is not lucky because my cluster can not update. Are there some workarounds? Thank you.

**Comment by vikin91** [comment]
Oh, it must be possible to upgrade Sensor if Central is already on version 4.5. What is your scenario? Are you upgrading from a particular version or is this a new installation?

**Comment by ThuanLee** [comment]
> Oh, it must be possible to upgrade Sensor if Central is already on version 4.5. What is your scenario? Are you upgrading from a particular version or is this a new installation?

I installed Central in OCP 4.14 and Secured Cluster on OCP 4.10 which max version of RHACS is 4.2. In my situation, it is impossible to upgrade OCP.

**Comment by vikin91** [comment]
Unfortunately, both OCP 4.10 and Sensor 4.2 are no longer officially supported.

There maybe some hacks that would help Sensor start, but there is no guarantee. Here are some things you could try:
- Starting Sensor with env variable set to `ROX_OFFLINE_MODE=true`
- Setting env variable `ROX_GRPC_MAX_MESSAGE_SIZE` for both Central and Sensor to something bigger than the value in the error - for example `ROX_GRPC_MAX_MESSAGE_SIZE=5000000` (most probably Sensor 4.2 will ignore this setting).
