### ISSUE TITLE
Scanner integration trivy

### ISSUE THREAD

**Issue by NissesSenap** [stackrox/stackrox#1400]
Today there are support for a number of registries and scanners.
Personally I use [trivy](https://github.com/aquasecurity/trivy) to scan my images using my CI/CD environment and to be consistent with existing vulnerabilities towards my developers I would like to use trivy as a image scanner.

Trivy can be run in client server mode https://www.youtube.com/watch?v=tNQ-VlahtYM and with a simple api request you can information about CVE:s in your container.

**Comment by md2119** [comment]
@NissesSenap, we appreciate your feedback!
I have directed your feedback to the appropriate engineering team. Once it has been discussed and evaluated, we will update this issue.

**Comment by msugakov** [comment]
Hi @NissesSenap 
Sorry for the long time waiting. The question about integrating trivy as StackRox scanner was discussed internally and the outcome is that it's not in plans for the StackRox team. The team has focus on evolving StackRox own scanner and deepening its integration with the rest of the product.

**Comment by NissesSenap** [comment]
That makes sense. I will close the issue.
Thanks for the update @msugakov
