### ISSUE TITLE
Provide a way to easily build collector drivers

### ISSUE THREAD

**Issue by Molter73** [stackrox/stackrox#1527]
Currently, the collector component of stackrox uses a kernel module or eBPF probe (referred to as drivers from this point on), in order to gather information on running processes, network connections, etc.

Because these drivers need to be build for a specific kernel, members of the community would either need to:
- Run stackrox in one of the platforms we support (we do support most major distributions as well as cloud providers).
- Run stackrox with collector disabled/in a crashloop, missing some of the stackrox functionality.
- Build their own driver and supply it to stackrox at runtime.

The last point is the subject of this issue, I believe it would be a nice addition to have a user friendly way for community members to compile their own drivers. Some of the potential solutions for this I can think of:
- Provide a docker image that could be run with the kernel headers and collector code mounted on it, leaving the complied drivers in the host. This could further be improved with a make target to not only compile the drivers, but also tag a collector image with those drivers embedded in it and ready to be used in a local deployment. Alternatively we could come up with a way to create a support package with those same drivers that could be uploaded to central through roxctl.
- Create a way for users to add kernels to be compiled and distributed through channels similar to how we distribute our supported drivers. This is similar to how Falco maintains their community drivers, but it would incur in extra expenses and effort for stackrox to support and maintain said system.

There are of course some extra wrinkles that might need to be ironed out, for instance some kubernetes test tools provide their own VM with the kernel headers for it distributed as a layer in a separate image, but I think having a simple approach (even if somewhat clunky initially) could encourage the community to build and improve upon it.

**Comment by Maddosaurus** [comment]
To provide a bit more context: 

We are currently collecting information to create a matrix of Kubernetes flavors and kernel versions that we are supporting.
As soon as we have this, we would like to explore how we could best integrate community contributions and ideally collect them in a single place to lessen the risk of repeating development efforts. 

For the moment, we'd be happy to use this issue to discuss possible paths we can take and get a first idea of additional platforms the community is interested in 🎉

**Comment by Molter73** [comment]
This is probably obsolete now that we have CO-RE BPF. @stackrox/collector-team should we close it?
