### ISSUE TITLE
Condition to evaluate central deployments' readiness

### ISSUE THREAD

**Issue by wpessers** [stackrox/stackrox#1545]
Currently, stackrox has a couple of possible `ConditionReason`s we can use to check if the Central is healthy. These are defined in https://github.com/stackrox/stackrox/blob/332c589ce23576052c755b90ac9ccc32b8f74c25/operator/apis/platform/v1alpha1/common_types.go#L68-L85

We use GitOps through ArgoCD and implemented this custom health check for the Central CRD:
![image](https://user-images.githubusercontent.com/45464718/166632144-8af29980-2d62-4ebe-8e1f-278252cadf66.png)

The problem is, that the InstallSuccessful ConditionReason is set before the deployments, managed by central, are healthy:![image](https://user-images.githubusercontent.com/45464718/166722838-06ec59af-acc8-4292-a84f-898e1ebc630e.png)

Ideally we'd want the the central resource to only show as healthy after its deployments (and other resources it manages) are healthy as well. I would propose to implement the existing conditions with a some sort of "Ready" ConditionReason, for when all the other resources managed by central are healthy.

**Comment by viswajithiii** [comment]
Hi @wpessers, thanks for filing this issue! I've pinged the operator experts on our team, and one of them will respond here soon.

**Comment by porridge** [comment]
Hi @wpessers as you have discovered, the operator does not monitor the health of its operands. The conditions in Central CR only reflect how recent reconciliation went.
We don't have plans to provide monitoring via the operator in the immediate future. However we would definitely like to know what could make your life easier. Would a single condition that reflects the health of all owned deployments be sufficient? What values would make sense in case of complete and partial health degradation? How would ArgoCD react if some deployment went unhealthy for a reason unrelated to latest rollout?

**Comment by wpessers** [comment]
Hello @porridge a condition that reflects the health of all owned deployments would indeed be what we need in this case. Ideally, we'd want the securedclusters to be created after all central deployments are healthy. Right now the securedclusters already start syncing before this condition is met.

It would be nice to be able to differentiate between the health central deployment and the other deployments. Even if a deployment becomes unhealthy for a reason unrelated to the latest rollout, we'd want this to carry over to the central CRD and be able to show it as unhealthy too.
