### ISSUE TITLE
Sensor pod crashed

### ISSUE THREAD

**Issue by Turgut202** [stackrox/stackrox#1640]
Hello,
I am using Stackrox in k8s approx 1-2 weeks. Today Sensos pod crashed (CrashLoopBackoff). Logs give me the following. Please help

No certificates found in /usr/local/share/ca-certificates
No certificates found in /etc/pki/injected-ca-trust
main: 2022/05/10 11:38:35.261465 main.go:28: Info: Running StackRox Version: 3.69.x-569-g769804636a
kubernetes/sensor: 2022/05/10 11:38:35.265931 sensor.go:73: Info: Loaded Helm cluster configuration with fingerprint "fb12e0e60b6db042d0d52966999774256e7eb3c88aea8bc1af00694346927bae"
kubernetes/sensor: 2022/05/10 11:38:35.296520 sensor.go:91: Info: Determined deployment identification: {
  "systemNamespaceId": "3582c397-0ae3-11ea-8402-067ff35c4130",
  "defaultNamespaceId": "36b49dc0-0ae3-11ea-8402-067ff35c4130",
  "appNamespace": "stackrox",
  "appNamespaceId": "21cc6be0-3b8f-45d7-a6d8-a40360aa0db8",
  "appServiceaccountId": "fb6f0e86-3634-48f4-9437-f2e8a864496b",

**Comment by SimonBaeumer** [comment]
Hey @Turgut202,
is this the whole log? To me it looks like there is something missing after `"appServiceaccountId": "fb6f0e86-3634-48f4-9437-f2e8a864496b",`.

**Comment by Maddosaurus** [comment]
For completeness, there is also [discussion on this issue happening over in the CNCF StackRox channel](https://cloud-native.slack.com/archives/C01TDE3GK0E/p1652182832572189).
The solution there was to reinstall using a different script. Current status of that thread: Waiting for result of recommended path.

**Comment by Turgut202** [comment]
Problem solved, i used another way of installation

**Comment by Maddosaurus** [comment]
That is great to hear, thanks for reporting back! :tada:
