### ISSUE TITLE
Compiling scanner missing builder image

### ISSUE THREAD

**Issue by msierks** [stackrox/stackrox#1695]
Hello, I'm trying to build/compile the scanner, which seems to require the image stackrox/scanner:builder-${BUILD-DIR_HASH} or in the case of CI quay.io/rhacs-eng/scanner:builder-$(BUILD_DIR_HASH).

https://github.com/stackrox/scanner/blob/master/Makefile#L26-L32

Both of these appear to be inaccessible, is this builder image accessible somewhere else or does it need to be generated through other means?

**Comment by gavin-stackrox** [comment]
> Both of these appear to be inaccessible, is this builder image accessible somewhere else or does it need to be generated through other means?

Hi Michael, I think `make scanner-image-builder` will provide that for you.

**Comment by msierks** [comment]
I think I see the problem, I've been getting this error: 

 ```
Unexpected docker pull error: Error response from daemon: pull access denied for stackrox/scanner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Which is triggering the script to die immediately instead of building the image. The specific logic I;m getting stuck on is located here:

https://github.com/stackrox/scanner/blob/master/scripts/ensure_image.sh#L29-L31

Not entirely sure what the best solution is here though.

**Comment by gavin-stackrox** [comment]
I tried to deconstruct it but I'm hitting an error with the build: 
```
$ docker build -t stackrox/scanner:builder-"$(git ls-files -sm build | git hash-object --stdin)" -f build/Dockerfile build/
[+] Building 2.8s (5/9)
 => [internal] load build definition from Dockerfile                                                                                                      0.1s
 => => transferring dockerfile: 37B                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/centos:8                                                                                               0.5s
 => CACHED [1/6] FROM docker.io/library/centos:8@sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177                                  0.0s
 => ERROR [2/6] RUN yum update -y && yum install -y epel-release dnf-plugins-core                                                                         2.1s
------
 > [2/6] RUN yum update -y && yum install -y epel-release dnf-plugins-core:
#5 1.937 CentOS Linux 8 - AppStream                       30  B/s |  38  B     00:01
#5 1.945 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
------
executor failed running [/bin/sh -c yum update -y && yum install -y epel-release dnf-plugins-core]: exit code: 1
```

**Comment by gavin-stackrox** [comment]
maybe @RTann can help us

**Comment by msierks** [comment]
Not sure what's going on with the centos:8 mirrors, though if I'm not mistaken that release is EOL. Switching to rockylinux:8 could be a quick workaround.

**Comment by RTann** [comment]
The stackrox repo (this one) builds the `main` image's binaries in a `centos:stream8` image in publicly accessible quay.io repos. Thank you for posting this issue, as it encouraged me to copy that concept over to the scanner repo. I will respond back to this issue once that is complete.

**Comment by RTann** [comment]
Scanner is now build by using a `quay.iostackrox-io/apollo-ci:scanner-build-<version>` image in the Scanner repo. This image should be public, so I don't expect more build issues. Feel free to close the issue @msierks if you are able to build the Scanner image locally

**Comment by msierks** [comment]
Thanks @RTann, much appreciated. This is working as expected.
