### ISSUE TITLE
Scanner build-updater generate-dump pulls from private gcs bucket

### ISSUE THREAD

**Issue by msierks** [stackrox/stackrox#1748]
When executing scanner build-updater generate-dump as part of the build instructions, it attempts to pull data from the stackrox-scanner-feed gcs bucket.

`./bin/updater generate-dump --out-file image/scanner/dump/dump.zip`

Which results in the following error:

```
ERRO[0050] an error occurred when fetching update        error="StackRox updater cannot be run without a service account" updater name=stackrox
```

Though I did not supply a gsa, I would think I'd need to request access to this bucket if I did. Would it make sense to use a publicly accessible endpoint instead? Let me know if I'm completely off base here.

**Comment by Maddosaurus** [comment]
Hey @msierks!
We've run into this problem on multiple occasions in the recent past.
Currently, we're working on a way to retire this private bucket, so you're not off base 😄 
We'll let you know once we've come up with a solution for this!

**Comment by connorgorman** [comment]
@RTann This shouldn't be a problem anymore right?

**Comment by RTann** [comment]
Correct, as of last week this bucket is now public. I will close this issue, but please feel free to reopen it if there are still any issues!
