### ISSUE TITLE
Scanner localdev error tar unexpected EOF

### ISSUE THREAD

**Issue by msierks** [stackrox/stackrox#1749]
When running scanner localdev against some test images results in the following the following error.

```
ERRO[0014] error reading "079bc5e75545bf45253ab44ce73fbd51d96fa52ee799031e60b65a82e89df662/layer.tar": EOF
```

After doing some digging if I increase the tarutils maxLazyReaderBufferSize to something large enough to avoid disk, the tar is read successfully. I suspect there might be an issue with the disk backed buffer.

**Comment by RTann** [comment]
Thank you for submitting this issue! Is there an example image you would not mind sending over, so we can look into it?

**Comment by msierks** [comment]
Sure, I exported the latest version of `rockylinux:8`. If you want I could supply the export itself, through some other means. The issue is when extracting an archive larger than the buffsize. In the case of rockylinux:8 it's approx 238MB.

I spent some time looking into this and it seems there might be an issue with diskBackedLazyReaderAt, possibly within ensureOverflowToDisk(). I don't fully understand all the logic here, but it results in not reading the entire file into the temp file.

https://github.com/stackrox/scanner/blob/master/pkg/ioutils/lazy_reader_disk.go#L191

**Comment by RTann** [comment]
I believe this is due to a bug in the Scanner codebase. I have created a ticket https://issues.redhat.com/browse/ROX-10991 to track it. Thank you very much for discovering this and letting us know!

**Comment by RTann** [comment]
The [fix has been merged](https://github.com/stackrox/scanner/pull/740). Please feel free to close the ticket if you no longer see this error. Thank you again for bringing this to our attention!

**Comment by msierks** [comment]
Confirmed, this is working now. Thanks.
