### ISSUE TITLE
PSP not needed on OpenShift

### ISSUE THREAD

**Issue by mmurhamm** [stackrox/stackrox#2357]
Helm charts 70.0.0 create PSP resources when installing on OpenShift where PSP are not available/needed. Suggestion to remove PSP when detecting installation to OpenShift.

**Comment by Maddosaurus** [comment]
Hi @mmurhamm and thank you for opening the issue!

You are correct in that StackRox 3.70 installs these even where they are not available.
With 3.71 we are introducing capabilities (and autodetection) whether they are needed or not.
You can find a more detailed description in the changelog for 3.71: https://github.com/stackrox/stackrox/blob/master/CHANGELOG.md#3710

I am closing this issue for now, but please feel free to reopen it, should you have further questions or if I have not addressed your report completely!
