### ISSUE TITLE
3.71.0 Not in Helm Charts

### ISSUE THREAD

**Issue by chalbersma** [stackrox/stackrox#2506]
Hey I noticed that 3.70 is the only version in the helm chart. Is that expected?

**Comment by mtesseract** [comment]
Hello!
Thanks you for your question.
Version 3.71.0 has not *yet* been released, but the release should be available pretty soon.
After the release process is finished you should be able to find updated Helm charts for v3.71.0.
Greetings,
Moritz

**Comment by mtesseract** [comment]
Hi again,
good news, 3.71.0 has been released yesterday and you can find the updated Helm charts here: https://github.com/stackrox/helm-charts/tree/main/3.71.0.
Therefore I will close this ticket.
Feel free to re-open or create a new one, in case something remains unclear.
Thanks,
Moritz
