### ISSUE TITLE
Cannot use OpenShift OAuth with OKD 4.8

### ISSUE THREAD

**Issue by dan-m8t** [stackrox/stackrox#2692]
Hi,

I am trying to set up Stackrox with OpenShift OAuth as as Auth providers.

When I try to add the provider I'll get the following error:

`unable to create an auth provider instance: unable to create backend for provider id xxxx-xxx-xxxx-xxxx: failed to create dex openshiftConnector for OpenShift's OAuth Server: failed to query OpenShift endpoint: Get "https://openshift.default.svc/.well-known/oauth-authorization-server": Service Unavailable`

I am not sure where StackRox get this endpoint from, I guess this is hardcoded?

The central pod logs shows nothing regarding this task.

What can I provide to solve the issue?

OKD version: 4.8
StackRox: 3.71 installed via Helm

Regards

**Comment by dhaus67** [comment]
Hey @dan-m8t, thanks for filing this issue!

As you rightly assumed, we currently have [this endpoint hardcoded within the implementation of the OpenShift auth provider](https://github.com/stackrox/stackrox/blob/ce907f6451177918d63536ad507f4dfe8b5d7fa6/pkg/auth/authproviders/openshift/backend_impl.go#L23). I don't have much experience with OKD, but I would assume the endpoints are surely different.

The best way would be to auto-detect specifically whether we are running within an OKD / OpenShift environment, but we currently do not plan to spend efforts to support OKD the same way we do OpenShift. This would also require a bigger effort.

A quick fix for this would be to define the endpoint the OpenShift auth provider uses as an environment setting, defaulting to `https://openshift.default.svc` (e.g. `ROX_OPENSHIFT_AUTH_ENDPOINT=https://okd.default.svc`). [Here is the enable openshift auth setting as an example.](https://github.com/stackrox/stackrox/blob/master/pkg/env/openshift.go#L12)

You could add the environment variable through helm setting the value `customize.central.envVars="ROX_OPENSHIFT_AUTH_ENDPOINT=<custom-endpoint` without requiring additional changes ([see here for the example](https://github.com/stackrox/stackrox/blob/d653406651df4331a714839ec2c0a23a93425c64/image/templates/helm/stackrox-central/values-public.yaml.example#L361-L367)).

I'd be happy to review the PR if you find the time to create one.

**Comment by dan-m8t** [comment]
Hey,

thanks for your response!
OKD and OpenShift are pretty close because OKD is the upstream project to OpenShift. So I'd assume the endpoints do not differ.

Anyways I figured out that I misconfigured my proxy settings and after reconfiguring the proxy setting I was able to save the auth provider with no error.

But when I choose OpenShift OAuth to login I get another error message from https://oauth-openshift.apps.mycluster.local:

`{"error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.","state":"1c21eb11-cd1e-49af-a499-253447c2713d:#"}`

Any hint where to take a look? 


Thanks

**Comment by dan-m8t** [comment]
Everything's fine, I should stick the docs ;).

My fault was that I forgot to enable the OpenShift Route in the Helm chart, so I configured my own to access stackrox. I bet the redirectURI is somewhere hardcoded. I enabled the Route via Helm and now it works as expected, thx!
