### ISSUE TITLE
Remove deprecated license flag in roxctl

### ISSUE THREAD

**Issue by dhaus67** [stackrox/stackrox#3059]
The command in question, `roxctl central license`, is deprecated and safe to remove.

For this, one would have to do the following:
- remove the files under [roxctl/central/license](https://github.com/stackrox/stackrox/tree/master/roxctl/central/license)
- remove all references of the command (such as [roxctl/central/central.go](https://github.com/stackrox/stackrox/blob/master/roxctl/central/central.go) and [roxctl/help/help.properties](https://github.com/stackrox/stackrox/blob/master/roxctl/help/help.properties))

Link to internal JIRA issue: [ROX-11058](https://issues.redhat.com/browse/ROX-11058)

**Comment by Schuermi7** [comment]
I'd like to work on this one. Pls assign this to me

**Comment by Maddosaurus** [comment]
Welcome @Schuermi7  and thanks for expressing interest into StackRox!
Feel free to take up the issue and having a look at it.
If you'd like, you can always link the branch of your fork if you have questions or need help, as the PR only counts towards Hacktober if it's opened after October 1st 😸

**Comment by Schuermi7** [comment]
I was working on it, but did not finish until the PR arrived, so please merge his then and unassign me.
