### ISSUE TITLE
clair endpoint for integration

### ISSUE THREAD

**Issue by yuanlinios** [stackrox/stackrox#3060]
Which clair endpoint is supposed to be used for the integration with stackrox? 

I've a clair instance running, but use a bare `hostname` or `https://hostname` in the Endpoint configuration just gives 404

**Comment by misberner** [comment]
Hey @yuanlinios , it depends on what endpoint you have configured your Clair instance to listen on.

I don't have first-hand experience running Clair (v4, I assume?), but from https://access.redhat.com/documentation/en-us/red_hat_quay/3.3/html/manage_red_hat_quay/clair-v4 I deduce that 8080 seems to be a common port for the HTTP API. So, depending on whether or not Clair is configured for TLS, the correct value here would be `https://hostname:8080` or `http://hostname:8080`.

**Comment by RTann** [comment]
Our Clair integration was originally built with Clairv2, and I do not believe it supports Clairv4 (unless the endpoint is the same). From the looks of it, [we use the `GET /layers/<layerName>` endpoint from Clairv2](https://github.com/stackrox/stackrox/blob/master/pkg/scanners/clair/clair.go#L125), which, I believe, [assumes Clairv2 already completed the scan separately](https://github.com/quay/clair/blob/v2.1.8/api/v1/routes.go#L145). We simply just retrieve the results.

**Comment by yuanlinios** [comment]
Thank you for the information
