### ISSUE TITLE
roxctl generate netpol adds`status: {}` metadata. Breaks kubectl apply command.

### ISSUE THREAD

**Issue by mfosterrox** [stackrox/stackrox#3405]
The generated network policy YAML files contain the `status: {}` metadata at the bottom of the files.

When using the `kubectl apply -f` command, it generates a `error: error validating "FILE": error validating data: ValidationError(NetworkPolicy): unknown field "status" in io.k8s.api.networking.v1.NetworkPolicy; if you choose to ignore these errors, turn validation off with --validate=false`

I can either delete the metadata or use `--validate=false` to get around it, but it is a minor annoyance. 

kubectl version: `WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+3afdacb", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-05-10T16:30:48Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Maddosaurus** [comment]
The output is directly generated by [NP-Guards Cluster Topology Analyzer](https://github.com/np-guard/cluster-topology-analyzer), so maybe we should check in with the team there whether they have an idea.
Could you (re)open this ticket over in their repo and see what they think? Thanks!

**Comment by vikin91** [comment]
This issue is worth another test after this is merged: https://github.com/stackrox/stackrox/pull/3696
