### ISSUE TITLE
Nil pointer ref in nvdCvssv2ToProtoCvssv2

### ISSUE THREAD

**Issue by adamrdrew** [stackrox/stackrox#3508]
Hello! We were trying to get stackrox set up on OpenShift and ended up with crash loop backoff for the central pod with a nil pointer ref:

```
cve/fetcher: 2022/10/20 17:11:29.292137 manager_impl.go:55: Info: successfully copied preloaded CVE istio files to persistent volume: "/var/lib/stackrox/cve/istio"
cve/fetcher: 2022/10/20 17:11:29.292242 orchestrator.go:62: Info: Found 0 clusters to scan for orchestrator vulnerabilities.
cve/fetcher: 2022/10/20 17:11:29.293043 orchestrator.go:237: Info: Successfully fetched 0 Kubernetes CVEs
cve/fetcher: 2022/10/20 17:11:29.293278 orchestrator.go:237: Info: Successfully fetched 0 OpenShift CVEs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x33d357d]
goroutine 140 [running]:
github.com/stackrox/rox/central/cve/converter/utils.nvdCvssv2ToProtoCvssv2(0x0)
github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:173 +0x1d
github.com/stackrox/rox/central/cve/converter/utils.NvdCVEToEmbeddedCVE(0xc00fcc4f40, 0x1)
github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:128 +0xd1
github.com/stackrox/rox/central/cve/converter/utils.NvdCVEsToEmbeddedCVEs({0xc00f5f4210, 0x16, 0x0?}, 0x15117?)
github.com/stackrox/rox/central/cve/converter/utils/convert_utils.go:219 +0x97
github.com/stackrox/rox/central/cve/fetcher.(*istioCVEManager).updateCVEs(0xc00090e300?, {0xc00f5f4210, 0x16, 0x16})
github.com/stackrox/rox/central/cve/fetcher/istio.go:71 +0x45
github.com/stackrox/rox/central/cve/fetcher.(*istioCVEManager).initialize(0xc002d7d030)
github.com/stackrox/rox/central/cve/fetcher/istio.go:46 +0xc5
github.com/stackrox/rox/central/cve/fetcher.(*orchestratorIstioCVEManagerImpl).initialize(0xc00f5ca8c0)
github.com/stackrox/rox/central/cve/fetcher/manager_impl.go:58 +0x2ba
github.com/stackrox/rox/central/cve/fetcher.NewOrchestratorIstioCVEManagerImpl({0x722b3e0?, 0xc0095e4000}, {0x0?, 0x0}, {0x7221d20?, 0xc002d7cf50}, {0x721c1c8?, 0xc00f5c5d00}, 0xc00f5db200)
github.com/stackrox/rox/central/cve/fetcher/manager.go:72 +0x372
```
There was likely something wrong with our config or setup, but figured yall would want to know about a panic. To me it looks the problem is that the pointer to the `BaseMetricV2` passed into the method that panicked was nil. The problem may be here?

```golang
if nvdCVE.Impact != nil {
		cvssv2, err := nvdCvssv2ToProtoCvssv2(nvdCVE.Impact.BaseMetricV2)
```

This was on a new setup. Central was installed but Secure Cluster wasn't set up yet. Tagging in @xxlhacker because he did the setup and may know more than me!

**Comment by Maddosaurus** [comment]
Hi @adamrdrew and thank you for the report!
From a quick glance (and the fact this happened to you recently), I strongly suspect the culprit for this to be the same as in https://github.com/stackrox/stackrox/issues/3503.
The source for this was a change in the CVE format that we process, so your analysis is very much on point! 💯 
[More details and recovery instructions are in this comment](https://github.com/stackrox/stackrox/issues/3503#issuecomment-1285606356).

Could you check whether the linked recovery instructions yield you a a running central, should your deployment still be up?

**Comment by hairmare** [comment]
@Maddosaurus i just ran into this issue with `quay.io/stackrox-io/main:3.72.0` and the linked mitigation steps worked and i now have a working central again.

**Comment by Maddosaurus** [comment]
As this issue has been quiet for a bit, I'll close it off as done in the hopes that it helped everyone involved.
@adamrdrew If you still experience issues, please feel free to reopen!
