### ISSUE TITLE
ERROR:  generating new init bundle: rpc error: code

### ISSUE THREAD

**Issue by HarryStarLord** [stackrox/stackrox#3738]
While generating init bundle for secured service i recieved the following error. 
```
ERROR:  generating new init bundle: rpc error: code = AlreadyExists desc = generating new init bundle: adding new init bundle to data store: init bundle already exists
command terminated with exit code 1
```
The command I ran: 
```
 kubectl -n stackrox exec deploy/central -- roxctl --insecure-skip-tls-verify   --password "${STACKROX_ADMIN_PASSWORD}"   central init-bundles generate stackrox-init-bundle --output - > stackrox-init-bundle.yaml
```

I dont know what i am doing wrong ??

**Comment by janisz** [comment]
Initbundle with name `stackrox-init-bundle` already exists. Could you try creating one with different name?

**Comment by HarryStarLord** [comment]
hey @janisz i tried but still the same error, moreover after deleting redeploying whole stackrox, old data keep showing. Whereas it suppose to start fresh

**Comment by porridge** [comment]
@HarryStarLord were you able to resolve this issue? Do you still need help?

**Comment by Maddosaurus** [comment]
@HarryStarLord I'm closing the issue for now, but feel free to comment/reopen at any time if you would like to continue disussing! 😄
