### ISSUE TITLE
Removed k8s API's in stackrox resources 3.72.2

### ISSUE THREAD

**Issue by Elyytscha** [stackrox/stackrox#3858]
The following resources are removed since k8s v1.21

![image](https://user-images.githubusercontent.com/10408311/203060568-86c054bc-9ea6-454d-a908-5480df11cb70.png)

this should be fixed in my opinion

**Comment by msugakov** [comment]
Hi @Elyytscha 

We've made updates for PSPs generation, and so it shouldn't happen for newer versions of k8s. The support for PSPs wasn't removed completely though, and in some cases they may be generated.
In order for us to be able to investigate this further, could you please let know how do you deploy StackRox: with Helm charts, with Operator, with `deploy/(k8s|openshift)/deploy.sh`?

Thanks!

**Comment by msugakov** [comment]
Also, please check this documentation that describes when PSP generation is in place and how to control that https://docs.openshift.com/acs/3.72/release_notes/372-release-notes.html#psp-changes

**Comment by msugakov** [comment]
IIRC, `deploy.sh` (and `deploy-local.sh`) doesn't auto-sense PSPs support therefore you will need to disable generation explicitly. The last command will change to:

```sh
POD_SECURITY_POLICIES=false MAIN_IMAGE_TAG=3.72.2 ./deploy/k8s/deploy.sh
```

Alternatively, you may try Helm charts deployment (either with [script](https://github.com/stackrox/stackrox/blob/master/README.md#quick-installation-using-helm) or [manual](https://github.com/stackrox/stackrox/blob/master/README.md#manual-installation-using-helm)). Helm charts should have auto-sensing of PSPs support on the cluster, plus this does not require cloning StackRox repo.

Please let know how it goes!
