### ISSUE TITLE
CVE scanning for node in 3.73

### ISSUE THREAD

**Issue by balpert89** [stackrox/stackrox#3891]
Hi all,

referring to an older [issue](https://github.com/stackrox/stackrox/issues/2676#issuecomment-1242545685) I wanted to check in if it is still planned to reactivate Node Scanning capabilities for CoreOS nodes in 3.73?

Best regards!

**Comment by vikin91** [comment]
@balpert89 , I am coming back to you with an answer: the CoreOS node scanning feature will be released in version v4.0 that is planned to be released in May 2023.

**Comment by balpert89** [comment]
@vikin91 many thanks for the update. Are there any updated helm charts for v4 RCs to be found or do I just change the images for all involved containers? Coming from 3.74.1.
