### ISSUE TITLE
Adding Specific standards to StackRox Other than default standards

### ISSUE THREAD

**Issue by srikavyakamma** [stackrox/stackrox#3965]
Can we add other standards to the Stack Rox other than default standards like HIPAA, NIST, PCI. If yes what is the process looks like ?

**Comment by sthadka** [comment]
Could you please share more details about which standards you are interested in and reasoning around it?

**Comment by srikavyakamma** [comment]
NIST 800-53 Moderate and High to offer reports to clients who need one or the other

FedRAMP Moderate and High to offer MSP or SaaS capabilities and audit the Solution

*less important: DoD IL4, IL5 to offset the difficulty of IL4 and IL5

**Comment by sthadka** [comment]
Thank you for the response. I've forwarded the request to our PM team, but things could be to be slower around the holidays.

**Comment by srikavyakamma** [comment]
Thank you, Will wait for your reply.

**Comment by sthadka** [comment]
Update: We internally use the [Compliance Operator](https://github.com/ComplianceAsCode/compliance-operator) for the compliance checks. The [ComplianceAsCode](https://github.com/ComplianceAsCode) GitHub org has all the code that goes in, specifically, the repository [ComplianceAsCode/content](https://github.com/ComplianceAsCode/content) has all the profiles for the different standards across the different operating systems.
There is also a [workshop](https://github.com/ComplianceAsCode/content/blob/master/docs/workshop/README.adoc) for getting started with setting up new rules.
Hope this helps!
