### ISSUE TITLE
Image Repo Docker to Quay

### ISSUE THREAD

**Issue by mlinarik** [stackrox/stackrox#4191]
When adding a new secured cluster the generated yaml download files still reference docker and need updated to quay. I'm not a developer so I'm not sure how to contribute. Here's the lines that need updated:

cat collector.yaml | grep image
        image: "**docker.io/stackrox**/collector:3.72.2"
        imagePullPolicy: Always
        image: "**docker.io/stackrox**/main:3.72.2"
        imagePullPolicy: IfNotPresent

**Comment by msugakov** [comment]
Hi @mlinarik 
Could you please confirm how you generated these files? Did you use new New Cluster creation in the StackRox UI and downloaded zip archive from there or did you use `roxctl` cli, or something else?
Thanks!

**Comment by md2119** [comment]
**The issue will be closed in the next 24 hrs if no response is received.**
