### ISSUE TITLE
Invalid Client Encoding for PostgreSQL

### ISSUE THREAD

**Issue by rfizzle** [stackrox/stackrox#4481]
The`client_encoding` type `UTF-8` set via the GORM config [here](https://github.com/stackrox/stackrox/blob/0bb35d9baa9674bed3b5b8f99cf08c0e4d39f780/migrator/postgres/gorm/config.go#L53) is invalid. Postgres defines it as `UTF8` per the [docs](https://www.postgresql.org/docs/15/multibyte.html#MULTIBYTE-CHARSET-SUPPORTED). This is causing connection failures in some environments.

```
panic: simple protocol queries must be run with client_encoding=UTF8
Error creating table for "*schema.Versions": simple protocol queries must be run with client_encoding=UTF8
```

This is part of a larger issue around how the database is configured. The full connection string is dependent on injected params in code (ex. `password` and `client_encoding`) and in the helm templates (`statement_timeout`, `pool_min_conns`, `pool_max_conns`). This is causing problems with non vanilla postgres environments. The full connection string should be configurable and not have injected values to prevent these issues.

Example: When using a connection pooler like PGBouncer, parameters like `statement_timeout` are not supported and cause a hard fail error on connection.

**Comment by janisz** [comment]
- https://github.com/stackrox/stackrox/pull/2615#issuecomment-1206308628

**Comment by rfizzle** [comment]
Will this be included in the next release? I haven't seen it applied to any of the Release Candidates.

**Comment by connorgorman** [comment]
@rfizzle I will close this ticket as the UTF8 issue is fixed, we are working towards addressing the other configuration issues described above
