### ISSUE TITLE
probe 1.0.0/collector-5.4.228-131.415.amzn2.x86_64.ko.gz does not exist in upstream

### ISSUE THREAD

**Issue by mszlgr** [stackrox/stackrox#4761]
Although 5.4.228-131.415.amzn2.x86_64 is listed in supported kernel versions - [link](https://github.com/stackrox/collector/blob/242e6aa82ac7783856e4cb8b67aab8f19dd39ea6/kernel-modules/KERNEL_VERSIONS#L5438) - I'm getting error:
```
pkg/probeupload: 2023/xx/xx xx:xx:xx server_handler.go:99: Info: kernel probe 1.0.0/collector-5.4.228-131.415.amzn2.x86_64.ko.gz not found
pkg/kocache: 2023/xx/xx xx:xx:xx source.go:60: Error: probe 1.0.0/collector-5.4.228-131.415.amzn2.x86_64.ko.gz does not exist in upstream https://collector-modules.stackrox.io/xxx
```

**Comment by Molter73** [comment]
Hi @mszlgr,

I believe that probe version corresponds with StackRox version 3.70, is this the version you are using? This version reached EOL in December, so we are no longer building drivers for it. You will need to update your StackRox installation, I see the probe is built for 3.71+.

**Comment by mszlgr** [comment]
Nice guess! This is exactly the case, tested and works with updated stackrox.
Thank you, closing
