### ISSUE TITLE
Clusters not eligible in the Network Graph section

### ISSUE THREAD

**Issue by SitoRBJ** [stackrox/stackrox#4898]
Hello everyone!

After upgrading via Helm Charts to version 3.73.2 we no longer see our K8S clusters in the Network Graph section but we are able to see them in other sections such as Dashboard or filter by them without any problem.

Do you know what could be happening?

- Network Graph

![image](https://user-images.githubusercontent.com/8913336/219331632-6c9bf38d-c85b-42dc-bbf1-335982cd9141.png)

![image](https://user-images.githubusercontent.com/8913336/219331867-8a13bf94-5a91-481f-bda0-ef3575752868.png)

- Dashboard (here we can see our clusters without problem)

![image](https://user-images.githubusercontent.com/8913336/219332423-11bbbe9c-9961-4be4-bb71-46119fb19686.png)

Regards

**Comment by kurlov** [comment]
@stackrox/ui do you know what could be the issue?

**Comment by vjwilson** [comment]
@SitoRBJ 
Please open your browser dev tools, and look at the network traffic when you navigate to the Network Graph page.
Filter by Fetch/XHR requests, and look for the API call that ends in `v1/clusters`. Let us know if it is returning an error, or just empty response.

**Comment by SitoRBJ** [comment]
Hello @vjwilson!!

Thank you for your prompt response. I can see the clusters in the request response.

![image](https://user-images.githubusercontent.com/8913336/219435659-4aead0fb-7c07-4cf7-b33b-860449602ced.png)

**Comment by kurlov** [comment]
Hello @SitoRBJ

Unfortunately, we were not able to reproduce the described issue on our environment. 
It looks like we need more information about your setup. I would suggest to contact the Red Hat support.
Also, do you have any specific characters in your cluster name? It could be escaping issue
