### ISSUE TITLE
Query: alerting devs/groups of devs based on which image the violation occurred against

### ISSUE THREAD

**Issue by mtcolman** [stackrox/stackrox#5019]
Hello, is it possible to configure policies to send to different endpoints/different user emails etc based on which image the violation occurred against? And can this occur across all areas of the lifecycle (build, deploy and runtime). I can see I can use annotations in deployment.yaml, which I presume covers deploy and runtime, but what about when scanning image in pipeline, as I can't use the deployment annotation for that.

For example, Dev-1 manages dev-one:1, Dev-2 manages dev-two:1. If the violation, for example, "curl present in image" triggers for dev-one:1, I only want Dev-1 to be notified, and if it occurs with dev-two:1, I only want Dev-2 to be notified etc.

Thanks!

**Comment by ovalenti** [comment]
Hello @mtcolman!

There has been some discussion regarding your request internally, we did not forget about it :)

Let me see if I can find the outcome and share with you.

**Comment by ovalenti** [comment]
Hello @mtcolman, here is what clues I could gather from that internal talk:
- there is a `--send-notifications` option to the roxctl image check command. It defaults to false. When specified, notifications will be sent via configured notifiers on the policy, should a build time policy result in an alert.
- it should be possible to make policy clones - each with the required scope (down to the deployment level) - and define a specific notifier there.

**Comment by boazmichaely** [comment]
Hi @mtcolman thanks for the question! 
Indeed, as you correctly called out, Stackrox can use deployment annotations to target notification. Also as you correctly called out,  deploy and run time policies have access to the offending deployment, while build time policies do not.
Indeed for deploy and run time, you can use  `--send-notifications` as @ovalenti pointed out, with which you can target a categtory of policies. So you would be able to group the policies you care about in a custom category and generate the desired notifications for Dev1 and Dev2 seperately. 
As you may be aware, we have introduced a new object in Stackrox called "Collection" which is intended to make it easy to identify team ownerships as in your use case. Today a Collection can point to  "deployments" (in the Stackrox term). In the future we plan to expand collections to also point to images and other Kubernetes resources. In addition, we are working to improve policy management in a way that leverages collections to provide more granular control of the policy behavior. You would be able define unique behavior per policy per collection. Specifically, you would be able to say "I want to use `DavesNotifier` when `policy-X` hits `DavesImages`     where DavesImages is a collection that defines the images owned by Dave's team, and `DavesNotifier` is a notifier that only sends emil to Dave. You would not need to rely on annotations to determine how those notificatiosn are sent, and indeed be able to apply this to build time images

**Comment by mtcolman** [comment]
Thanks both @ovalenti and @boazmichaely, that's all useful to know. I don't suppose you have any view (by quarter, half, year etc) when the more granular alerting for build time violations will be available?

**Comment by mtcolman** [comment]
Also, I've just installed ACS 3.74 and I cannot find Collections? It says "To use collections, click Platform Configuration → Collections. The page displays a list of currently-configured collections. You can perform the following actions:" (taken from [here](https://docs.openshift.com/acs/3.74/operating/create-use-collections.html#access-object-collections_create-use-collections), but I don't have "Collections" listed under Platform Configuration.

![ACS](https://user-images.githubusercontent.com/33348891/224000953-5fa1ec2a-bdd4-4fb4-be3b-bdcaf12109fa.jpg)

**Comment by porridge** [comment]
@boazmichaely any comments from your side?

**Comment by md2119** [comment]
@mtcolman The collections feature is GA starting 4.0. Please upgrade to 4.0 to see the feature.

**Comment by msugakov** [comment]
Hi @mtcolman
Do you have any feedback to share about the feature, i.e. whether it fits your use-case?

**Comment by porridge** [comment]
Closing this inactive issue. Please reopen if 4.x does not address your needs.
