### ISSUE TITLE
smtpserver and port should be splitted using net.SplitHostPort

### ISSUE THREAD

**Issue by amedeos** [stackrox/stackrox#5125]
Currently smtpserver and port are splitted using fmt.Sprintf[0], instead, as net packages is already imported, could be useful and more resilient to use net.SplitHostPort, as alertmanager does[0]

https://github.com/stackrox/stackrox/blob/b739c343071784237e6ee3fde48594cddedfec54/central/notifiers/email/email.go#L120

https://github.com/openshift/cluster-monitoring-operator/blob/eb426eb5deadb22c2216901bca11e2ca9db49f54/vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go#L897

**Comment by janisz** [comment]
@amedeos The host and port are not splitted but concatenated in this line. How can we improve it then?
