### ISSUE TITLE
server and port should be splitted using net.SplitHostPort

### ISSUE THREAD

**Issue by amedeos** [stackrox/stackrox#5128]
Central calculate server and port using custom code[0], maybe this could be improved using net.SplitHostPort as alermanager does[1]

[0] Central code:
https://github.com/stackrox/stackrox/blob/3.74.0/central/notifiers/email/email.go#L156-L167

[1] alertmanager code:
https://github.com/openshift/cluster-monitoring-operator/blob/eb426eb5deadb22c2216901bca11e2ca9db49f54/vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/amcfg.go#L897

**Comment by RTann** [comment]
From what I can tell, `net.SplitHostAndPort` returns an error if the port is missing. We want to allow a missing port, so we may use a default. If we use `net.SplitHostAndPort`, we'd have to check to make sure the error is related to missing the port. I'm not sure if replacing the current implementation with `net.SplitHostAndPort` adds much value.

I'm going to close this issue, but feel free to reopen it, if needed.
