### ISSUE TITLE
Unable to Disable PodSecurityPolicy

### ISSUE THREAD

**Issue by crimv42** [stackrox/stackrox#5479]
Version 74.1.0

Error:
```Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: [resource mapping not found for name: "stackrox-admission-control" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "stackrox-collector" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "stackrox-sensor" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first]
helm.go:84: [debug] [resource mapping not found for name: "stackrox-admission-control" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "stackrox-collector" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "stackrox-sensor" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first]```

**Comment by vjwilson** [comment]
@crimv42 
Can you give us some more details about the environmental you are seeing these errors in?
1. Which installation method are you using to install StackRox?
2. Which flavor and version of Kubernetes are you using?

In the meantime, if you are using the `roxctl central generate...` method, you could try this workaround to get past this issue:

> Manually remove any *pod-security.yaml files after extracting the .zip file

**Comment by SimonBaeumer** [comment]
@crimv42 
This looks like Helm or Operator because of the Helm log entry.

1. Are you using `helm template` to generate the StackRox manifests?
2. Can you share the Kubernetes and OpenShift version are you using?

**Comment by crimv42** [comment]
@Maddosaurus Unfortunately that resulted in the same error

**Comment by Maddosaurus** [comment]
@crimv42 Sorry to hear that, but thanks for testing! We have a colleague working on this on an internal ticket and will update you as soon as there are any insights!

**Comment by ludydoo** [comment]
Hello @crimv42 , 

I unfortunately failed to reproduce the issue you are mentioning. I assume that you've followed the installation documents [here](https://docs.openshift.com/acs/3.74/installing/installing_ocp/install-central-ocp.html#installing-quickly_install-central-ocp).

This cluster I tested this on is GKE `v1.25.7-gke.1000`

```bash
# Install Central helm version version 3.72
helm repo add rhacs https://mirror.openshift.com/pub/rhacs/charts/
helm install -n stackrox --create-namespace stackrox-central-services rhacs/central-services --version 72 --values values.yaml
helm install -n stackrox-secured --create-namespace stackrox-secured-cluster-services rhacs/secured-cluster-services -f values-secured.yaml --version 72

# > notice that the PodSecurityPolicies are disabled by reading the output
# - PodSecurityPolicies are disabled, since your environment does not support them according to API server properties.

# Upgrade to 3.74
helm upgrade -n stackrox stackrox-central-services rhacs/central-services --version 74 --values values.yaml
helm upgrade -n stackrox-secured stackrox-secured-cluster-services rhacs/secured-cluster-services --version 74 --values values-secured.yaml

# > Notice that the PodSecurityPolicies are still disabled
# - PodSecurityPolicies are disabled, since your environment does not support them according to API
  server properties.

# values.yaml
imagePullSecrets:
  username: <redacted>
  password: <redacted>
```

Would you be able to provide the detailed steps on how the upgrade was performed on your side, or any details that I might've missed? To speed up the resolution of this issue, I would propose that we schedule a short Google Meet (between 8-18 CET). Please feel free to reach me at my @redhat email address.

**Comment by ludydoo** [comment]
Hello @crimv42 , do you have any updates on this issue ?

**Comment by crimv42** [comment]
Still having this issue when trying to upgrade to 4.0. Sorry for the late reply. I would be down for a Google Meet. I will e-mail you and we can figure out a time.

**Comment by crimv42** [comment]
> ```shell
> helm mapkubeapis stackrox-central-services --namespace stackrox
> ```

This did it!! Thank you!

**Comment by Elyytscha** [comment]
not sure if we should close the issue, this (possibly) affects every stackrox installation which was installed before k8s cluster was on 1.25, after k8s upgrade to 1.25 this should occur 100% when someone tries to ugprade the stackrox installation.

which is caused by the installation logic which determines if k8s version is prior 1.25 and then uses psp's (but this only happens at install time, which causes this)

**Comment by Tokynet** [comment]
FWIW, this just happened to my bare-metal (Talos) installation running k8s v1.27.1

As of right now, I have no way to install Stackrox via Argocd. Now looking into building my own argocd container to add the helm plugin required.

**Comment by kovayur** [comment]
Because of the way `helm upgrade` works, there is not much we can do other than use `helm mapkubeapis` suggested above.

According to the [helm doc](https://helm.sh/docs/intro/using_helm/#helm-upgrade-and-helm-rollback-upgrading-a-release-and-recovering-on-failure)

> An upgrade takes an existing release and upgrades it according to the information you provide. Because Kubernetes charts can be large and complex, Helm tries to perform the least invasive upgrade. It will only update things that have changed since the last release.

Thus, helm fails to build kubernetes objects from the current release containing the PSPs, even before applying the actual upgrade:

```
unable to build kubernetes objects from current release manifest: [resource mapping not found for name: "stackrox-scanner" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "stackrox-admission-control" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "stackrox-collector" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" ensure CRDs are installed first, resource mapping not found for name: "stackrox-sensor" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" ensure CRDs are installed first
```

The [helm doc](https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest) also suggests to use the helm [mapkubeapis](https://github.com/helm/helm-mapkubeapis) plugin in such cases.

Nevertheless, we are going to add recovery from the same problem in the operator as it uses helm under the hood.

**Comment by porridge** [comment]
See above regarding mapkubeapis for helm-based installation.
For the operator, this is resolved by https://github.com/stackrox/stackrox/pull/6815
