### ISSUE TITLE
Support OCI Image Index Manifest for Vulnerability Scanning

### ISSUE THREAD

**Issue by rfizzle** [stackrox/stackrox#5635]
I am receiving an error when central is attempting to scan OCI images for vulnerabilities:

```
error: getting metadata from registry: "<REGISTRY>": unknown manifest type 'application/vnd.oci.image.index.v1+json'
```

**Comment by janisz** [comment]
Thank you for raising this issue.  I encountered a similar problem when attempting to scan `cgr.dev/chainguard/busybox:1`. 
In OCI docs we can read that we should support this media type.
> [The image index is a higher-level manifest which points to specific image manifests, ideal for one or more platforms. While the use of an image index is OPTIONAL for image providers, image consumers SHOULD be prepared to process them.](https://github.com/opencontainers/image-spec/blob/main/image-index.md#oci-image-index-specification)

The problematic function is: 
https://github.com/stackrox/stackrox/blob/173c70ff9c2c7a8f9b20955ce5b181436fc68f8d/pkg/registries/docker/docker.go#L194-L207

Internal tracker: ROX-16421

**Comment by RTann** [comment]
This has been resolved upstream, and will be released in 4.1.0. I'm going to close this issue, but feel free to reopen it if needed.

**Comment by janisz** [comment]
https://github.com/stackrox/stackrox/pull/5641

**Comment by RTann** [comment]
> We're still seeing this issue. Both with image `4.1.5` and `4.3.5` <img alt="Screenshot 2024-02-13 at 15 01 58" width="1776" src="https://private-user-images.githubusercontent.com/25441280/304435960-e4b20670-117b-4adf-b1b4-1a1f10a35bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NjYwMjYsIm5iZiI6MTcwNzg2NTcyNiwicGF0aCI6Ii8yNTQ0MTI4MC8zMDQ0MzU5NjAtZTRiMjA2NzAtMTE3Yi00YWRmLWIxYjQtMWExZjEwYTM1YmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDIzMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YmY1YzE3Y2IyYWY0ZWRiYjEyOTY4NWIzYmY4ZGZkZGRmNzE1OGQyYjE3MTU1MmYzYTNmZjVmYWY3MWFmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uKBNSJx63dsFw4jRmxx6P8nBwrodiDAg3gyM2No8m6E">
> 
> Is this related or should i open a new issue?

I believe this is a separate issue, which we will need more information about. Since it looks like you are using ACS, instead of upstream StackRox I recommend using the typical customer support channels for that, thanks
