### ISSUE TITLE
Existing image integration not found

### ISSUE THREAD

**Issue by joachimBurket** [stackrox/stackrox#5670]
We have an image integration to a JFrog artifactory Docker repository:

Integration Name: JFrog - Docker local
                   Endpoint: docker-local.jfrog.ourdomain.com

When we run the image scan in our CICD with

```bash
roxctl --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT image check --image docker-local.jfrog.ourdomain.com/app-images/my-app:1.0.0
```

it works for a time, and after some weeks, we got the following error:

```bash
ERROR:	Checking image failed: could not check build-time alerts: rpc error: code = Internal desc = image enrichment error: checking for matching registries for image "docker-local.jfrog.ourdomain.com/app-images/my-app:1.0.0": not found: no matching image integrations found: please add an image integration for "docker-local.jfrog.ourdomain.com/app-images/my-app:1.0.0". Retrying after 3 seconds...
```

By deleting and re-creating the image integration, the error disappears, but after a while it breaks again.

Any idea about that?

Stackrox version: v3.74.1
Roxctl version: 3.74.1

**Comment by dhaus67** [comment]
Hey @joachimBurket !

Sorry for the late answer on that one.

It'd be great to get some more additional information about this to try and figure out where the issue could potentially be.

I'd be specifically interested in the API response of the image object.

You can use either basic authentication with the admin username + password or [an API token](https://docs.openshift.com/acs/4.0/configuration/configure-api-token.html) for authentication, and the request would be:
```bash
curl https://<your-central>/v1/images/sha256:<digest of your image>

e.g.
curl https://<your-central>/v1/images/sha256:ee128bb6d355792c136aad236faead2906c7410933b41e4a05c4d4be19f04401
```

In case you don't know the SHA of your image you could use something like this:
```bash
curl https://<your-central>/v1/images | jq -r '.[] | select(.name == "docker-local.jfrog.ourdomain.com/app-images/my-app:1.0.0
")'
```

**Comment by joachimBurket** [comment]
Hi @dhaus67!

Thanks for your late answer (mine wasn't that quick too 😅 ).

We didn't have the issue for a long time, and last week it re-appeared (for the record, we are now in stackrox v4.0.2). I hadn't the time to run the API command when the error occured, and fixed it by deleting and re-adding the JFrog integration.

I have tested the curl command, and will keep it on hand for the next time the issue appear.

**Comment by porridge** [comment]
@joachimBurket do you think it would make sense to close this issue now, and reopen if it occurs again and you have more information to add? 🤔

**Comment by joachimBurket** [comment]
Hi! Yes you can close it, we didn't have the issue for a long time, so hopefully it won't appear anymore :)
