### ISSUE TITLE
UI Bug in Safari - Policy Creation

### ISSUE THREAD

**Issue by rfizzle** [stackrox/stackrox#5722]
I experience a UI issue while trying to create a policy in OSX Safari v16.4 and Stackrox v3.74.0.

Reproduction Steps:

1. Open Policy Creation in Safari
2. Proceed to the second page and choose the `Runtime` lifecycle stage
3. Attempt to choose the `Event Sources`. You are unable to select the radios

I've noticed it is a dynamic element that usually shows/hides based on the selected lifecycle stage, however, it is always showing at the bottom of the form in Safari. You also get some weirdness if you choose the `Inform and Enforce` response option.

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/2577744/232662872-cc95c649-31c3-46c4-aa0e-0f4428b20c02.png">

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/2577744/232663150-7226a77a-c7d8-44ba-a004-f9f04ef49914.png">

**Comment by vjwilson** [comment]
@rfizzle The fix for this, #7768, was just merged and will be released in version 4.3, which should be out in late November of this year.
