### ISSUE TITLE
Run scanner closer to the clusters and able to push result to central.

### ISSUE THREAD

**Issue by flowdopip** [stackrox/stackrox#5790]
Following the Stackrox architecture:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/5880313/233713412-1e010e11-4b0e-4f6e-b8c7-d8d7ded58f26.png">

The scanner component is only available next to the Central and scans the images that all sensors report to the central services. If the Kubernetes clusters are across regions ( Europe, the US or others) and each region has a dedicated registry, the scanner will try to pull images from all registries across all regions and can impact the bandwidth available across regions.

The goal is to try to have a dedicated scanner in each cluster consuming the local registry and report the results to central.

**Comment by RTann** [comment]
This is something we are currently in the process of doing, especially when image registries are only accessible from within specific clusters or at least not accessible from the Central Cluster.

**Comment by flowdopip** [comment]
Hi, thanks @RTann.

Any idea when it became available? It's something that we can collaborate to delivery ASAP?

**Comment by flowdopip** [comment]
Hi,
Any news?
Any roadmap to share with the community?

**Comment by md2119** [comment]
@flowdopip we do not have a roadmap to share with the community. As Ross pointed out this feature is being worked on and will be released soon. Please continue checking the release announcements.

**Comment by flowdopip** [comment]
Any news here?

**Comment by dcaravel** [comment]
Hi @flowdopip , with the 4.1 release this capability has been added - configurable via the API only (for now). For details lookup `DelegatedRegistryConfigService` in the API reference within the UI.

It requires a slim version of `scanner` to be installed in the secured cluster(s), which has been the default in OCP clusters (for some time now) and shown in the [architecture docs](https://docs.openshift.com/acs/4.1/architecture/acs-architecture.html#acs-architecture-differences-ocp-kube_acs-architecture):
![image](https://github.com/stackrox/stackrox/assets/119438707/7fe5d637-241f-489f-8175-9f28388e144a)

With the 4.1 release, `scanner slim` can now be installed in non-OCP secured clusters (via helm). That combined with the configuration mentioned above - registry interactions can be set to occur via the secured clusters as desired.
