### ISSUE TITLE
Misleading information given from help for CA flag

### ISSUE THREAD

**Issue by jacobosborne1** [stackrox/stackrox#5798]
If you run roxctl --help it will say the --ca flag wants a string. This is false as it wants a filepath.

**Comment by janisz** [comment]
It was addressed in https://github.com/stackrox/stackrox/pull/5731 do you think the current message is better or we should improve it?

https://github.com/stackrox/stackrox/blob/1a042f26ecf90eeb1cf0b504a81952605e2f102e/roxctl/common/flags/endpoint.go#L72-L73

Maybe it should be something like:

> Path to a custom CA certificate to use (PEM format).  Alternatively pass the file path using the ROX_CA_CERT_FILE environment variable

@dhaus67 What do you think?

**Comment by dhaus67** [comment]
> @dhaus67 What do you think?

Yeah, think that's totally reasonable.

@jacobosborne1 do you want to create a PR for that? Should be a rather straightforward change, as @janisz pointed out the line that'd need changing. We'd be happy to review it 😄
