### ISSUE TITLE
[v4] collector container "node-inventory" fails because binary is not available

### ISSUE THREAD

**Issue by balpert89** [stackrox/stackrox#5921]
The `4.0.0` collector pod fails with the following event:

```
Error: container create failed: time="2023-05-04T18:23:07Z" level=error msg="runc create failed: unable to start container process: exec: \"/scanner\": stat /scanner: no such file or directory"
```

Debugging the container shows there is no binary:
```
sh-4.4$ ls -la /scanner 
ls: cannot access '/scanner': No such file or directory
```

Image: quay.io/stackrox-io/main:4.0.0
Environment: OCP 4.12.10

**Comment by vikin91** [comment]
Hi @balpert89 , the `node-inventory` container should use the `scanner-slim` image, not the `main`. Could you share how you installed this? Was this upgrade of existing cluster or a fresh installation? Have you been using Helm or k8s manifests?

**Comment by balpert89** [comment]
I have used helm to install and update central. I have been following https://docs.openshift.com/acs/4.0/upgrading/upgrade-helm.html#upgrade-helm-chart_upgrade-helm for the update procedure. The secured cluster is created by an API call and then the zip archive is downloaded and applied to the target cluster.

I believe the configuration for the secured cluster is wrong (?) for our use case. Bit of context: we have to mirror the images to another registry that is whitelisted for our environments, let's call that `registry.internal.com`. We configure the cluster for `Main Image Repository` to `registry.internal.com/paas/stackrox/stackrox` (an image would be e.g. `registry.internal.com/paas/stackrox/stackrox:4.0.0`) and `Collector Image Repository` to `registry.internal.com/paas/stackrox/collector`. This apparently confuses the manifest generation and it ends up setting the node-inventory container image to `registry.internal.com/paas/stackrox/stackrox:4.0.0`. In earlier versions this was not a problem but bites us now for v4.

I have created a `test` cluster object where I set `Main Image Repository` to `registry.internal.com/paas/stackrox`, this is the result (<component>/<container name>: <image>):

admission-controller/admission-control: `registry.internal.com/paas/stackrox:4.0.0`
collector/collector: `registry.internal.com/paas/collector:4.0.0`
collector/compliance: `registry.internal.com/paas/stackrox:4.0.0`
collector/node-inventory: `registry.internal.com/paas/stackrox:4.0.0`
sensor/sensor: `registry.internal.com/paas/stackrox:4.0.0`

![image](https://user-images.githubusercontent.com/28100685/236419553-57c2154d-b7da-4b2b-888d-fcca930de5b9.png)

**Comment by balpert89** [comment]
Yes, just confirmed this. When setting the `Main Image Repository` to `registry.internal.com/paas/stackrox/main` the node-inventory image is properly set to `registry.internal.com/paas/stackrox/scanner-slim:4.0.0`. I have to adapt our pipelines for this and will report back when done.

**Comment by vikin91** [comment]
Ok, I see, thanks for this is useful information. So the installation method that you described is using generated manifests - one can either generate them through `roxctl sensor generate` or directly the API call. If I remember correctly, the image reference used for `node-inventory` shall always be the same as the image for `main` but the image name part `main` will be replaced with `scanner-slim`. So if you configure the system to use `main` from `registry.internal.com/whatever/main:4.0.0`, the `node -inventory` should be using  `registry.internal.com/whatever/scanner-slim:4.0.0`.

If you discover any combination that results in something else, please let us know how to reproduce it. (Of course, I will check the scenario that you posted in the screenshot).

**Comment by balpert89** [comment]
Yes we have misinterpreted the `Main Image Repository` where we believed this is meant to act as the base for all the images, not only for the central (or main, for that matter :-D).

**Comment by vikin91** [comment]
Ah, I see! I do not think we have a way of providing such a "base" for all registries. You need to spell out fully the main image repository (including the image name: `main`) and the rest will be derived from it (whereas collector image repo could be overridden if wanted).

**Comment by balpert89** [comment]
I have done that, pipeline runs successfully and the central + secured clusters are now running properly on v4 :+1: thank you for the hint, I am going to close the issue.

**Comment by vikin91** [comment]
For all people who are here with the same problem: there is indeed a bug in version 4.0.0 for some particular combinations of installation methods. 

The fix is to patch the `node-inventory` image from `main` to `scanner-slim`. Here an example of the patch command for the image originating from the official Red Hat registry:

```
kubectl -n stackrox patch ds/collector -p '{"spec":{"template":{"spec":{"containers": [{"name":"node-inventory","image":"[registry.redhat.io/advanced-cluster-security/rhacs-scanner-slim-rhel8:4.0.0](http://registry.redhat.io/advanced-cluster-security/rhacs-scanner-slim-rhel8:4.0.0)"}]}}}}'
```
