### ISSUE TITLE
 Prometheus - Deprecated APIs removed in 1.25 

### ISSUE THREAD

**Issue by pruthvibs164** [stackrox/stackrox#6127]
`>>> Deprecated APIs removed in 1.25 <<<
------------------------------------------------------------------------------------------
KIND                  NAMESPACE     NAME                                             API_VERSION      REPLACE_WITH (SINCE)
PodSecurityPolicy     <undefined>   kube-prometheus-stack-alertmanager               policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy     <undefined>   kube-prometheus-stack-kube-state-metrics         policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy     <undefined>   kube-prometheus-stack-operator                   policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy     <undefined>   kube-prometheus-stack-prometheus                 policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy     monitoring    kube-prometheus-stack-grafana                    policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy     monitoring    kube-prometheus-stack-grafana-test               policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy     monitoring    kube-prometheus-stack-prometheus-node-exporter   policy/v1beta1   <removed> (1.21.0)`

When I ran kubent in my cluster, I got that these APIs are removed in 1.25. What is the solution for these..?

Thanks,

**Comment by porridge** [comment]
@pruthvibs164 these do not seem to be related to stackrox. Can you please explain why you think otherwise?

**Comment by msugakov** [comment]
Hi @pruthvibs164 
Kindly ping

**Comment by porridge** [comment]
Closing inactive issue, please feel free to reopen when you have more updates.
