### ISSUE TITLE
CIS docker Compliance Scanning always shows 100% for EKS and AKS

### ISSUE THREAD

**Issue by sanjeeveejayabalan** [stackrox/stackrox#6128]
CIS docker compliance scanning not working for both EKS and AKS clusters. It shows N/A when export compliance report.

**Comment by connorgorman** [comment]
Hi @sanjeeveejayabalan, can you please provider information about the version of the cluster that you are using and also the runtime. You can get this info by doing something like so:

```
kubectl get node <node name> -o json | jq .status.nodeInfo
```

**Comment by sanjeeveejayabalan** [comment]
let you check it

{

  "architecture": "amd64",
   "containerRuntimeVersion": "containerd://1.6.6",
  "kernelVersion": "5.4.219-126.411.amzn2.x86_64",
  "kubeProxyVersion": "v1.24.7-eks-fb459a0",
  "kubeletVersion": "v1.24.7-eks-fb459a0",
  "operatingSystem": "linux",
  "osImage": "Amazon Linux 2",

}

**Comment by sanjeeveejayabalan** [comment]
![RHACS](https://github.com/stackrox/stackrox/assets/122220065/b50448af-eaa5-4d76-a01b-8176cc83219f)
@connorgorman  Few docker controls are applicable to containerd runtime as well. When we are creating the following controls in policies, it's validating our deployments and provide findings for the same,

Few controls for reference,
4.1 - Ensure that a user for the container has been created
5.15 - Ensure that the host's process namespace is not shared
5.7 - Ensure privileged ports are not mapped within containers

Why those controls are excluded in docker compliance scanning, is there any way to fix this issue?

Applicable controls screenshot attached for your reference.  Can we able to create cutomized applicable controls to scan the k8s?

**Comment by sanjeeveejayabalan** [comment]
@connorgorman We are urging you to fix this, please let me know the exact fix.

**Comment by sanjeeveejayabalan** [comment]
We are urging to fix this, please let me know the exact fix.

**Comment by dashrews78** [comment]
This issue is quite stale and aside from that compliance is being rethought and reworked.
