### ISSUE TITLE
kernel module issue

### ISSUE THREAD

**Issue by anandku87** [stackrox/stackrox#6240]
I am trying to test stackrox installation on my homelab deployed with vmware tanzu. It is vmware photon based kubernetes cluster.  
stackrox version 3.74.3 and having below events in collector logs - 
[INFO    2023/05/31 11:58:23] Attempting to download kernel object from https://sensor.stackrox.svc:443/kernel-objects/2.5.0-rc1/collector-ebpf-4.19.247-7.ph3.o.gz
[INFO    2023/05/31 11:58:23] HTTP Request failed with error code 404
[WARNING 2023/05/31 11:59:53] Attempted to download collector-ebpf-4.19.247-7.ph3.o.gz 90 time(s)
[WARNING 2023/05/31 11:59:53] Failed to download from collector-ebpf-4.19.247-7.ph3.o.gz
[WARNING 2023/05/31 11:59:53] Unable to download kernel object collector-ebpf-4.19.247-7.ph3.o to /module/collector-ebpf.o.gz
[WARNING 2023/05/31 11:59:53] No suitable kernel object downloaded for collector-ebpf-4.19.247-7.ph3.o
[ERROR   2023/05/31 11:59:53] Failed to initialize collector kernel components.
[INFO    2023/05/31 11:59:53]
[INFO    2023/05/31 11:59:53] == Collector Startup Diagnostics: ==
[INFO    2023/05/31 11:59:53]  Connected to Sensor?       true
[INFO    2023/05/31 11:59:53]  Kernel driver candidates:
[INFO    2023/05/31 11:59:53]    collector-ebpf-4.19.247-7.ph3.o (unavailable)

can you please help how to get this support kernel module for photon os.

**Comment by anandku87** [comment]
I am using Collector Version: 3.14.x-81-g71847db676
Thanks for the update.

**Comment by md2119** [comment]
@anandku87, please close the issue if your question is addressed. 

**The issue will be closed in the next 24 hrs if no response is received.**
