### ISSUE TITLE
Protobuf version 22.0 has been de-published

### ISSUE THREAD

**Issue by 02fa** [stackrox/stackrox#6242]
https://github.com/stackrox/stackrox/blob/aed7c22602db7eb9220fe394376496373951926a/make/protogen.mk#L37

Build process fails:
```
make image
<snip>
+ /home/user/stackrox/go/src/github.com/stackrox/stackrox/.proto/.downloads/protoc-22.0-linux-aarch64.zip
curl: (22) The requested URL returned error: 404
<snip>
make[1]: *** [make/protogen.mk:75: /home/user/stackrox/go/src/github.com/stackrox/stackrox/.proto/.downloads/protoc-22.0-linux-aarch64.zip] Error 1
make[1]: Leaving directory '/home/user/stackrox/go/src/github.com/stackrox/stackrox'
make: *** [make/protogen.mk:82: /home/user/stackrox/go/src/github.com/stackrox/stackrox/.proto/protoc-linux-aarch64-22.0/bin/protoc] Error 2
```

I'd imagine release notes for adjacent protobuf versions have to be examined, and the closest non-breaking version needs to be in use here.

**Comment by md2119** [comment]
The issue is an incorrect arch string. The release does exist: https://github.com/protocolbuffers/protobuf/releases/download/v22.0/protoc-22.0-linux-aarch_64.zip

What is the output of `uname -m` on the machine where you are running `make image`?

**Comment by Maddosaurus** [comment]
@Wang-W-e-i Out of curiosity: Is 22.1 available for your arch? So if you bump the dependency in `protogen.mk` to 22.1, is the build process able to download the release?

With regards to what it does: Actually, big parts of our platform use it indirectly. `protoc` takes all the protocol definitions that we have and generates code stubs out of it. 
Almost all of our components talk to each other through gRPC, and these stubs are how that is done.
So we need to be a bit careful with bumping this dependency, as it is literally used everywhere 😄
