### ISSUE TITLE
Incorrect BUILD_IMAGE_VERSION in in 4.0.1 'branch'

### ISSUE THREAD

**Issue by 02fa** [stackrox/stackrox#6246]
https://github.com/stackrox/stackrox/blob/f303f4adc072f61d01f7eb015feb0ae75f17b78b/BUILD_IMAGE_VERSION#L1

If I clone 4.0.1 'branch', go version is stated incorrectly:
```
git clone --depth 1 --branch 4.0.1 https://github.com/stackrox/stackrox
cat stackrox/BUILD_IMAGE_VERSION 
**stackrox-build-0.3.57**
```

It's supposed to be `stackrox-build-0.3.58`. I'd guess the reason is that 4.0.1 doesn't exist as a branch, it's rather a tag.

Is it possible to update the tagged `BUILD_IMAGE_VERSION` retrospectively? Would it be a good idea to re-visit branching strategy to link it to releases and to make it inclusive of all the artefacts?

**Comment by vikin91** [comment]
Hi @Wang-W-e-i , thank you for asking!

I think the settings in the Github [branch for release `4.0`](https://github.com/stackrox/stackrox/blob/release-4.0/BUILD_IMAGE_VERSION) are correct. On that branch, we were using builder `0.3.57` and later patched that to `0.3.57.1`. The versions `0.3.58` and `0.3.59` (see https://github.com/stackrox/rox-ci-image/releases) include Go 1.20 and are meant for the 4.1 release.

Could you please explain why do you think the file should contain `stackrox-build-0.3.58` for the `4.0` release?
