### ISSUE TITLE
Incorrect EXPECTED_GO_VERSION in 4.0.1 'branch'

### ISSUE THREAD

**Issue by 02fa** [stackrox/stackrox#6247]
https://github.com/stackrox/stackrox/blob/f303f4adc072f61d01f7eb015feb0ae75f17b78b/EXPECTED_GO_VERSION#LL1

If I clone 4.0.1 'branch', go version is stated incorrectly:
```
git clone --depth 1 --branch 4.0.1 https://github.com/stackrox/stackrox
cat stackrox/EXPECTED_GO_VERSION
**go1.19.4**
```

It's supposed to be `go1.20.3`. I'd guess the reason is that 4.0.1 doesn't exist as a branch, it's rather a tag.

Is it possible to update the tagged `EXPECTED_GO_VERSION` retrospectively? Would it be a good idea to re-visit branching strategy to link it to releases and to make it inclusive of all the artefacts?

**Comment by vikin91** [comment]
I think, the situation you are observing is correct. Versions `4.0.0` and `4.0.1 `run on Go 1.19.4, whereas `4.0.2` runs on 1.19.9. Note, that there is only one branch for the `4.0` version; the patches (`4.0.z`) are available as tags. 

I hope my answer from #6246 provides some additional explanation.
