### ISSUE TITLE
collector in crashloopbackoff even upload support-packages to center

### ISSUE THREAD

**Issue by anandku87** [stackrox/stackrox#6323]
I am testing stackrox depoyment in offline mode. i have uploaded support-package to central.

but still below logs from central pod

```
sensor/service/pipeline/reconciliation: 2023/06/05 09:18:11.217217 reconciliation.go:148: Info: Reconciliation done. Number of objects deleted by type: map[*central.SensorEvent_Binding:0 *central.SensorEvent_ComplianceOperatorProfile:0 *central.SensorEvent_ComplianceOperatorResult:0 *central.SensorEvent_ComplianceOperatorRule:0 *central.SensorEvent_ComplianceOperatorScan:0 *central.SensorEvent_ComplianceOperatorScanSettingBinding:0 *central.SensorEvent_Deployment:0 *central.SensorEvent_Namespace:0 *central.SensorEvent_NetworkPolicy:0 *central.SensorEvent_Node:0 *central.SensorEvent_Pod:1 *central.SensorEvent_Role:0 *central.SensorEvent_Secret:0 *central.SensorEvent_ServiceAccount:0]
pkg/probeupload: 2023/06/05 09:20:25.161515 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:20:55.197985 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:21:25.238302 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:21:55.272804 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:22:25.306199 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:22:55.341783 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:23:25.374029 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
pkg/probeupload: 2023/06/05 09:28:21.940873 server_handler.go:99: Info: kernel probe 2.5.0-rc2/collector-ebpf-5.4.0-122-generic.o.gz not found
```

--------------------------------------------------------------------
I am using below versions -  

Collector Version: 3.14.x-147-g4c2aa9fd0a
OS: Ubuntu 20.04.4 LTS
Kernel Version: 5.4.0-122-generic

**Comment by msugakov** [comment]
Hi @anandku87

Besides the kernel version `5.4.0-122-generic`, the collector kernel driver version is important. It is a bit obfuscated but also present in the log message; the driver version is `2.5.0-rc2`. `-rc2` means it's pre-release, and pre-release drivers aren't usually published to the [support packages page](https://cdn.stackrox.io/collector/support-packages/index.html) so not really available for download as a package.

You may try using the latest release version of StackRox, i.e. 4.0.1 at the moment, or, if newer build of Collector is important, wait until 4.1.0 gets released and the support package for it (with 2.5.0 driver) becomes available for download.

Hope this helps

**Comment by anandku87** [comment]
@msugakov Thank you for your reply.  one question will it download compatible drivers if I connect Central to the internet, or any older version can I use for this to work.

**Comment by msugakov** [comment]
Unless you [explicitly configured](https://docs.openshift.com/acs/4.0/configuration/enable-offline-mode.html#enable-offline-mode-during-installation) Central to work in the offline mode, Central will attempt downloading drivers from StackRox endpoint. It may happen that certain kernels are new, and the automation hasn't yet built a driver for it. In that case, you should see errors fetching the driver logged in `central` pod logs.

I see that https://github.com/stackrox/collector/blob/master/kernel-modules/KERNEL_VERSIONS mentions `5.4.0-122-generic` and so it should work.

**Comment by msugakov** [comment]
Hi @anandku87 
Do you have anything to report or need any assistance in this issue, or can we close it?

**Comment by porridge** [comment]
Closing inactive issue, please feel free to reopen when you have more updates.
