### ISSUE TITLE
CIS Benchamarks fail on Kubelet checks when using Dynamic Kubelet config and not --config option

### ISSUE THREAD

**Issue by ssurovich** [stackrox/stackrox#6359]
Trying to use Stackrox for CIS benchmarking (to begin with) - Most of it works as expected, but every node is failing the checks that deal with the Kubelet options.   Stackrox throws an error that it couldnt find the Kubelet --config file, which makes sense here since it doesnt use the --config option to set anything.

Instead, it uses a ConfigMap that has those values set using kubelet_opt+=" --<values>"

Any chance of a workaround for deployments that dont use --config for Kubelets?

**Comment by dashrews78** [comment]
We have no workaround for this at the present time.  Additionally we are in the process of re-visioning how the benchmark checks work in general.
