### ISSUE TITLE
Collector pod privilege mode requirement reasons

### ISSUE THREAD

**Issue by naveen2131-hue** [stackrox/stackrox#6451]
As the Collector pod runs with Privilege mode, it affects the AWS security hub score due to this privilege permission of the pod. May I know, why the privilege mode is required for the collector pod?

**Comment by naveen2131-hue** [comment]
@ludydoo @vikin91 @amedeos @jvdm Kindly check the above issue.

**Comment by vikin91** [comment]
The privileged mode is essential for Collector to function properly. Let me ping the collector team to give you a more precise answer to that: @robbycochran @Stringy @Molter73 @erthalion @JoukoVirtanen @ovalenti

**Comment by naveen2131-hue** [comment]
Thanks for the update! @vikin91 @Stringy

**Comment by msugakov** [comment]
Hi @naveen2131-hue 
If the clarification was helpful, would it be ok to close this issue as completed?
