### ISSUE TITLE
Central crashing on baremetal startup

### ISSUE THREAD

**Issue by c0ldb00t3r** [stackrox/stackrox#6491]
Hi, 
    I have tried installing Central with the latest 4.0.2 helm chart.
provided custom options 

  exposure:
    nodeport:
      enabled: true
      port: 30069
  db:
    persistence:
      persistentVolumeClaim:
        storageClass: manual

![image](https://github.com/stackrox/stackrox/assets/10518727/b349d360-59a7-4129-b3a5-289b11bdeeb0)
![image](https://github.com/stackrox/stackrox/assets/10518727/ff15be1e-f229-4ac4-98ee-a2a43c7569d6)

**Comment by Maddosaurus** [comment]
Hi @c0ldb00t3r and thanks for the report!
Could you tell us a bit more about your storage configuration? 
My first hunch would be a permission issue, as the write fails.

**Comment by c0ldb00t3r** [comment]
@Maddosaurus I think the below screenshot would provide a better idea about storage
![image](https://github.com/stackrox/stackrox/assets/10518727/1dced5e6-4382-404e-9a58-27da80218142)

**Comment by ludydoo** [comment]
@c0ldb00t3r have you been able to solve the issue? If yes, could you let us know how did you solve the problem?

**Comment by c0ldb00t3r** [comment]
I did not find any solution. Neither are any installation guides for other clusters. I have tried in total 8 clusters, and faced the same problem everywhere. Thanks, I really can't spend more time on this
