### ISSUE TITLE
Stackrox Upgrade issue - Sensor pod connectivity Issue

### ISSUE THREAD

**Issue by naveen2131-hue** [stackrox/stackrox#6500]
After Upgrade both central and Secured cluster services the sensor, collector and admission controller pods are Unhealthy. Getting error as the certificate bundle that was generated from a different central installation.

@ludydoo @vikin91 @amedeos @jvdm @porridge

**Comment by vikin91** [comment]
Would you mind pasting the logs from sensor?

I suspect that Central was deployed without persistent storage and the certificates from the first installation are gone. Now, after the upgrade Sensor and Central cannot recognize each other.

I can confirm or deny that after we see some logs.

**Comment by naveen2131-hue** [comment]
The persistent storage is already exists and the old init bundle is exists in central dashboard.


![sensor logs](https://github.com/stackrox/stackrox/assets/117265644/660807e4-6bd6-4f57-a01c-0d8050422ca7)
@vikin91

**Comment by vikin91** [comment]
Yes, this is the reason I was speaking about: `using a certificate bundle that was generated from a different Central installation than the one it is trying to connect to`. You need to check the persistent storage for central for it to not happen in the future. 
Now, the fix is to use the correct bundle - could you try generating a new init bundle in Central and apply it to the secured cluster?

**Comment by naveen2131-hue** [comment]
@vikin91 Yes, we used the same PV for central. Also if I regenerate new bundle its working fine. 

Also we could able to see the old initbundles in dashboard.

**Comment by vikin91** [comment]
I think there is still a chance to delete the bundle while still being able to see it in the dashboard. I am not very familiar with the code for that, but I suspect that Central UI displays the bundle info based on the state of the database, while the certificates are stored on PVC. Deleting them from the PVC (or not having PVC at all) will cause the certs to be gone, while the bundle info will be visible in the UI. I think that this may be what has happened in your case.

**Comment by rukletsov** [comment]
@naveen2131-hue, Could you please let us know the following:
* what are the versions from which and to which you have been upgrading?
* what is your installation method?
* excerpt from the Central log containing errors for the failed verification of a connecting Secured Cluster

**Comment by naveen2131-hue** [comment]
![Db](https://github.com/stackrox/stackrox/assets/117265644/b5ae9fa3-3fc7-4c4d-a755-aefcb338312d)

Kindly review this photo and @vikin91 confirm us that are u talking about this.

**Comment by vikin91** [comment]
The data on the screenshot are for `central-db`. The PVC that has not been created (and caused that issue) is a different one and should be named `central`. Central and central-db are two different deployments.

**Comment by vikin91** [comment]
@naveen2131-hue have you maybe resolved this issue in the meantime?

**Comment by porridge** [comment]
Closing this stale issue.
Please reopen if you have more updates.
