### ISSUE TITLE
Central crashing due to OOM on AWS EKS after 4.0.1 upgrade

### ISSUE THREAD

**Issue by dunetrader** [stackrox/stackrox#6561]
Hey Team,

I would like to report an issue. The upgrade to 4.0.1 was successful, we can see the central-db and the scanner-db are in place. Stackrox is working fine. But the central pod is crashing due to an OOM error repeatedly every 10 to 15 mins. 

The logs for the central pod show an error in refreshing credentials for the ECR.
`pkg/registries/ecr: 2023/06/15 08:57:09.122242 ecr.go:130: Error: Error refreshing docker client for registry "Autogenerated AWS account xxxxxxxxxxxx and region us-east-1 for cluster xxxxxxxxxx": failed to refresh the auto-generated integration credentials`

The describe output gives the following events
`Readiness probe failed: Get "https://172.31.46.70:8443/v1/ping": dial tcp 172.31.46.70:8443: connect: connection refused`

We have done the ECR integration manually, and there is no need for sensors to trigger the refresh credentials API, but we didn't find any configuration setting to disable that.

We are running the setup using the Helm charts on an AWS EKS cluster. 

We have also tried to edit the resource limits for the central pod, with almost double what was defined initially, but no resolution.

**Comment by connorgorman** [comment]
This was resolved after bumping the memory and setting ROX_PROCESS_PRUNING to true on the Central deployment
