### ISSUE TITLE
Allow customizing `central` & `scanner` nodeAffinity in Helm chart

### ISSUE THREAD

**Issue by Roberdvs** [stackrox/stackrox#6622]
As of version 4.0.2, the deployment of the `central` & `scanner` components done by the stackrox Helm chart has [this](https://github.com/stackrox/helm-charts/blob/main/4.0.2/central-services/templates/01-central-13-deployment.yaml#L39-L71) nodeAffinity included without providing any option of customizing it.

One problem we're facing with those affinities is that they make the deployment incompatible with [Karpenter](https://github.com/aws/karpenter), which is ignoring the pods for scheduling because it treats labels under the `kubernetes.io` domains as restricted labels.

Karpenter log:
> 2023-06-22T08:13:16.103Z	DEBUG	controller.provisioner	**ignoring pod, label node-role.kubernetes.io/master is restricted; specify a well known label**: [karpenter.k8s.aws/instance-accelerator-count karpenter.k8s.aws/instance-accelerator-manufacturer karpenter.k8s.aws/instance-accelerator-memory karpenter.k8s.aws/instance-accelerator-name karpenter.k8s.aws/instance-category karpenter.k8s.aws/instance-cpu karpenter.k8s.aws/instance-encryption-in-transit-supported karpenter.k8s.aws/instance-family karpenter.k8s.aws/instance-generation karpenter.k8s.aws/instance-gpu-count karpenter.k8s.aws/instance-gpu-manufacturer karpenter.k8s.aws/instance-gpu-memory karpenter.k8s.aws/instance-gpu-name karpenter.k8s.aws/instance-hypervisor karpenter.k8s.aws/instance-local-nvme karpenter.k8s.aws/instance-memory karpenter.k8s.aws/instance-network-bandwidth karpenter.k8s.aws/instance-pods karpenter.k8s.aws/instance-size karpenter.sh/capacity-type karpenter.sh/provisioner-name kubernetes.io/arch kubernetes.io/os node.kubernetes.io/instance-type topology.kubernetes.io/region topology.kubernetes.io/zone], **or a custom label that does not use a restricted domain: [k8s.io karpenter.k8s.aws karpenter.sh kubernetes.io]**

It would be great if the nodeAffinity could be customized through the chart values while keeping the current one as the default value for retro-compatibility.

Cheers!

**Comment by Roberdvs** [comment]
Looks like there's already an ongoing PR tackling this https://github.com/stackrox/stackrox/pull/6470 ❤️

**Comment by SimonBaeumer** [comment]
Pull Request is merged: https://github.com/stackrox/stackrox/pull/6470

@Roberdvs Please reopen the PR in case something else is missing.
