### ISSUE TITLE
Is it possible to apply raw Falco rules?

### ISSUE THREAD

**Issue by NitroCao** [stackrox/stackrox#6664]
Currently it seems that we can create policies (rules) by using visual policy editor (Platform Configuration -> Policy Management), but it's not flexible, and we already have some Falco rules. So is it possible to apply raw Falco rules?

**Comment by Maddosaurus** [comment]
StackRox comes with its own rule engine, which means you cannot apply raw Falco rules.
But the good news is that there is a big effort underway to make policies way more flexible. 
Please keep an eye out for the "Collections" feature with regards to Policies in the release notes 😄

**Comment by msugakov** [comment]
Hi @NitroCao 

Sorry, it has been a while and you might have figured the answer yourself or gave up waiting.
The answer is: no, StackRox does not support raw Falco rules, and the support is not planned as far as I'm aware.

I'm closing this issue. Please feel free to follow-up with further comments in which case we can reopen it.

Thanks
