### ISSUE TITLE
is there any option to generate custom reports with cvss score

### ISSUE THREAD

**Issue by imdmahajankanika** [stackrox/stackrox#6877]

**Comment by rukletsov** [comment]
Hey @imdmahajankanika, could you please mention which report are you referring to? If you mean vulnerability reports, which version and what your request is: add CVSS score, filter by CVSS score during generation, etc.

**Comment by imdmahajankanika** [comment]
> Hey @imdmahajankanika, could you please mention which report are you referring to? If you mean vulnerability reports, which version and what your request is: add CVSS score, filter by CVSS score during generation, etc.

Hello @rukletsov, actually yes, I would like to have a filter for cvss score also when we generate a vulnerability report to send it via email.

Currently, we have options to filter by severity
, Fixable and namespaces but would it be possible to do have a column for cvss score also in the generated report?

I am using the latest version of stackrox (4.x)

**Comment by md2119** [comment]
@imdmahajankanika CVSS score column will be available in the vulnerability report soon. Do keep an eye out for the release announcements. The filter by CVSS capability is farther on the roadmap.

**Comment by imdmahajankanika** [comment]
> @imdmahajankanika CVSS score column will be available in the vulnerability report soon. Do keep an eye out for the release announcements. The filter by CVSS capability is farther on the roadmap.

@md2119 Thanks!
