### ISSUE TITLE
Add ability to write custom rules

### ISSUE THREAD

**Issue by sahaniarungod** [stackrox/stackrox#7030]
How can I create a new policy in policy management. For example like to have policy to audit the resource request and use in kubernetes.

**Comment by Maddosaurus** [comment]
In general, feel free to consult the [Downstream docs here for policy management](https://docs.openshift.com/acs/4.1/operating/manage-security-policies.html#create-custom-policies), as the functionality is identical to StackRox.
The easiest start would be to duplicate an existing policy and then modify the duplicate to your needs.

**Comment by sahaniarungod** [comment]
It works, but I cannot write the custom rule myself.

**Comment by md2119** [comment]
Hello @sahaniarungod, thank you for bringing the request to us. We have noted your request; however, support for custom policy rules is not planned for the near-term roadmap at least. We find this feature desirable; however, we are in the early stage.

@boazmichaely this is something to be considered during policy management rework.
