### ISSUE TITLE
While changing image tag, centraldb password has been changed

### ISSUE THREAD

**Issue by naveen2131-hue** [stackrox/stackrox#7103]
In this Version 4.1.0, while I'm trying to change my image tag! I'm getting this below error.

Migrator failed: failed to scan clones: failed to connect to `host=central-db.stackrox.svc user=postgres database=postgres`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))

Kindly suggest me to fix this error.
@ludydoo @vikin91 @amedeos @jvdm @porridge

**Comment by vikin91** [comment]
Your issue looks to me like a wrong password to the database. Could you check if you have a correct one in your setup?

I would suggest not to ping particular people in Github issues unless you know that these people directly worked on a given part of system. We read the Github issues and we have a schedule for acknowledging and answering, so I am sure that all of them will be attended to according to our SLAs.

**Comment by naveen2131-hue** [comment]
Roger that, Those centraldb password is auto generated. Then how comes it would be wrong. Initially it was working fine. Then after changing the image repo we figured out this error.

**Comment by connorgorman** [comment]
@naveen2131-hue Could you give us more details about how you are deploying?

**Comment by dashrews78** [comment]
What do the original and updated helm commands look like?

**Comment by naveen2131-hue** [comment]
This is newly installed with argo cd.

**Comment by dashrews78** [comment]
it might be important for us to see the helm options argo is passing.  Both for fixing and working around it.  For instance I can reproduce this by running a `helm upgrade` and including `--set central.db.password.generate=true` as that says to generate a new password.

**Comment by naveen2131-hue** [comment]
is this mandatory to set the value  --set central.db.password.generate=true for each helm update. While changing the image tag the argocd is generating the new password and the password is changed successfully, but while connecting its not accepting the new password. 
![stackrox](https://github.com/stackrox/stackrox/assets/117265644/684ec6a2-cebe-4d03-b2da-a110fe16f7c3)

**Comment by dashrews78** [comment]
no that setting should only be used on the initial install.

**Comment by porridge** [comment]
Closing inactive issue, please feel free to reopen when you have more updates.
