### ISSUE TITLE
Difference between rhacs/central-services and rhacs/stackrox-central-services?

### ISSUE THREAD

**Issue by naveen2131-hue** [stackrox/stackrox#7104]
can i know difference between central services and stackrox central services?
rhacs/central-services
rhacs/stackrox-central-services

**Comment by naveen2131-hue** [comment]
> can i know difference between central services and stackrox central services? rhacs/central-services rhacs/stackrox-central-services

can anyone give comparison between central services and stackrox central services?

**Comment by ebensh** [comment]
Hello, thank you for your question. Can you provide a bit more context that will help us answer your question - are you asking about the Helm chart or Operator services that can be installed, or a specific path in the repository, a Custom Resource you're looking at?

https://github.com/stackrox/helm-charts/blob/0e958846dfeadccca1bdf4414384bed4fea9175e/README.md?plain=1#L17 might help clarify

**Comment by naveen2131-hue** [comment]
![stackrox](https://github.com/stackrox/stackrox/assets/117265644/4e80298f-631d-4232-88e9-94e47ce5eead)

**Comment by vladbologa** [comment]
Hi @naveen2131-hue 

As per the Red Hat Advanced Cluster Security Documentation (see [here](https://docs.openshift.com/acs/4.1/installing/installing_ocp/install-central-ocp.html) or [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_security_for_kubernetes/4.1/html/installing/installing-rhacs-on-red-hat-openshift#adding-helm-repository_install-central-ocp)), the recommended charts are `rhacs/central-services` and `rhacs/secured-cluster-services`.

However `rhacs/stackrox-central-services` and `rhacs/stackrox-secured-cluster-services` are essentially aliases and they reference the same products as their non-stackrox prefixed equivalents.
