### ISSUE TITLE
Is there a feature to filter CVEs on in the running pods in the cluster

### ISSUE THREAD

**Issue by imdmahajankanika** [stackrox/stackrox#7244]
Hello, Today stackrox shows CVEs in all the images, deployments present in all the (system+user) projects of the cluster even if a deployment is scaled-down with 0 replica. Is there a way to filter the vulnerabilities only in the running pods of user-created projects?

**Comment by md2119** [comment]
@imdmahajankanika, stackrox does not currently support filtering CVEs by the deployment status. The team will give more thought to your request for a mid-term to long-term product roadmap.
