### ISSUE TITLE
cant be injected

### ISSUE THREAD

**Issue by Nello-Angelo** [stackrox/stackrox#7681]
some app cant be injected how fix this and can these apps work with side-car

![Screenshot_5](https://github.com/stackrox/stackrox/assets/82488489/d317a558-4f01-471b-994d-98e4120b0cba)

**Comment by Nello-Angelo** [comment]
i use linkerd

**Comment by mclasmeier** [comment]
Hi @Nello-Angelo, could you please elaborate? This issue doesn't have a lot of information and it makes it rather hard to understand what the issue you have observed actually is. Thank you.
