### ISSUE TITLE
can stackrox works with other service mesh? (linkerd)

### ISSUE THREAD

**Issue by Nello-Angelo** [stackrox/stackrox#7682]
i see integration only with istio

![Screenshot_7](https://github.com/stackrox/stackrox/assets/82488489/9f6ae615-deb1-4cc2-9bb2-cfe145b09d8a)
![Screenshot_6](https://github.com/stackrox/stackrox/assets/82488489/8a4862d0-810b-43c6-9608-8d8eb7823665)

**Comment by md2119** [comment]
We would only scan any linkerd containers to identify vulnerabilities in the images that those containers are using them. This is slightly different from our support istio support where we also detect istio versions running in secured clusters and then check against a list of known vulns for those istio versions.
