### ISSUE TITLE
Roxctl. generate netpol for Helm Charts

### ISSUE THREAD

**Issue by VenutNSA** [stackrox/stackrox#7700]
Hello, everyone!
Are there plans to include network policy generation for Helm Charts in the roadmap?
I don't know enough about the NP-Guard architecture. Where would it take to work with it to make it possible to generate policies for charts?

Generating policies in Pipelines for specific resources is very inconvenient and somewhat unusable:(

**Comment by vikin91** [comment]
Hi @VenutNSA , if I understand your problem correctly, then I think there is already a solution to it. Have you tried populating the Helm chart with `helm template` to obtain the manifests and then passing it to the NP-Guard function `roxctl generate netpol`?

**Comment by vjwilson** [comment]
Stale issue
