### ISSUE TITLE
Can collector pods connect to sensor via route instead of internal service

### ISSUE THREAD

**Issue by imdmahajankanika** [stackrox/stackrox#7743]
Hello,

I have remote nodes in my cluster and the collector pods on remote node are unable to connect to sensor pod via internal service "sensor.stackrox.svc:443". Is there a way to make this connection via route (as it is accessible externally)

Thanks

**Comment by kurlov** [comment]
@stackrox/collector-team could you please have a look?

**Comment by ovalenti** [comment]
@imdmahajankanika, this is a good question, and something I never considered; so thanks for bringing that up :sweat_smile: 

I believe that setting the SNI_HOSTNAME to the URL of you route would make Collector connect to you Sensor.

The helm charts have this value [carved in stone](https://github.com/stackrox/stackrox/blob/master/image/templates/helm/stackrox-secured-cluster/templates/collector.yaml#L55-L56). Thus, unless you modify the DaemonSet after deployment, I see no way to parameterize it for now.

This usually is unnecessary, since Sensor and Collector are deployed together. And k8s mandates that all the PODs on a cluster be able to communicate directly with each other. If your collectors cannot communicate with the Sensor, maybe it would be easier to create an other Sensor co-located with them.

Overall, it would turn "I have remote nodes in my cluster" into "I have 2 clusters" :smiley:

**Comment by ovalenti** [comment]
My bad, TIL that SNI_HOSTNAME is not the only parameter to contact Sensor.

@imdmahajankanika, if you set `sensor.endpoint` while installing via helm-charts ([doc](https://docs.openshift.com/acs/4.1/installing/installing_other/install-secured-cluster-other.html#secured-cluster-services-config_install-secured-cluster-other)), to contain the route+port of your Sensor, you may be able to make it work.

*However*, SNI_HOSTNAME will not reflect this change and Collector will have trouble to fetch the probes if it doesn't have them already. So this will only work with full-collector images, not with the slim flavor.

**Comment by imdmahajankanika** [comment]
> My bad, TIL that SNI_HOSTNAME is not the only parameter to contact Sensor.
> 
> @imdmahajankanika, if you set `sensor.endpoint` while installing via helm-charts ([doc](https://docs.openshift.com/acs/4.1/installing/installing_other/install-secured-cluster-other.html#secured-cluster-services-config_install-secured-cluster-other)), to contain the route+port of your Sensor, you may be able to make it work.
> 
> _However_, SNI_HOSTNAME will not reflect this change and Collector will have trouble to fetch the probes if it doesn't have them already. So this will only work with full-collector images, not with the slim flavor.

Hello @ovalenti I don't have two clusters. Actually, I have added a remote worker node into my existing cluster and the problem is that the pod on worker classic is unable to communicate with pod on remote worker node via a service internal to the cluster.

I tried to create an https route for sensor svc so that I can replace SNI_HOSTNAME in daemonset but the route is not working (Application not available).

**Comment by ovalenti** [comment]
@imdmahajankanika, my proposal was to set `sensor.endpoint`. If you do it by modifying directly the DaemonSet, then the environment variable is `GRPC_SERVER`.

On the other hand, when I was talking about 2 clusters, I was thinking that maybe you could declare the remote-worker node as one cluster in Stackrox, then co-locate a Sensor. This way, the communication would not have to go through a route anymore. But this is just an idea.

**Comment by imdmahajankanika** [comment]
> @imdmahajankanika, my proposal was to set `sensor.endpoint`. If you do it by modifying directly the DaemonSet, then the environment variable is `GRPC_SERVER`. Un
> 
> On the other hand, when I was talking about 2 clusters, I was thinking that maybe you could declare the remote-worker node as one cluster in Stackrox, then co-locate a Sensor. This way, the communication would not have to go through a route anymore. But this is just an idea.

Hello @ovalenti thanks for the explanation! Your idea sounds better rather than using route. Is there any documentation or procedure to do that ?

**Comment by ovalenti** [comment]
@imdmahajankanika, I gave it a bit more thinking, and you might be very unpractical to deploy daemonsets in parts of a k8s cluster. I am afraid that we get back to my original conclusion that k8s mandates that all the PODs in a cluster can freely communicate to each other: see https://kubernetes.io/docs/concepts/services-networking/#the-kubernetes-network-model.

**Comment by imdmahajankanika** [comment]
> @imdmahajankanika, I gave it a bit more thinking, and it might be very unpractical to deploy daemonsets in parts of a k8s cluster. I am afraid that we get back to my original conclusion that k8s mandates that all the PODs in a cluster can freely communicate to each other: see https://kubernetes.io/docs/concepts/services-networking/#the-kubernetes-network-model.

Yes @ovalenti , you are right that pods in a cluster can freely communicate via internal services. But, in case of a remote worker node addded to the same cluster, I am experiencing connection issues (time out) via internal services and I am unable to find the root cause. So, I am looking for a workaround because the collector pod running of remote node is in crashloopbackoff as it is unable to connect with sensor pod on classic worker node via internal service.

**Comment by porridge** [comment]
Am I reading it right @ovalenti  that stackrox does not support this? Should this issue be closed?

**Comment by ovalenti** [comment]
@porridge, yes, we support k8s clusters, and this topology does not fit the definition.
