### ISSUE TITLE
Update vulnerability definitions 

### ISSUE THREAD

**Issue by MrWazaby** [stackrox/stackrox#7815]
Hello, 

I can see in System Health that the update vulnerability definitions are ou of date on a fresh stackrox install.   
How can I update them manually? For information the last update is **2023-08-12T00:02:22.748570390Z**.

Thank you for your help.

**Comment by connorgorman** [comment]
@MrWazaby The database is initially filled with data from the time of the build, but will update after a while. Can you please check if this problem has persisted?

**Comment by MrWazaby** [comment]
Indeed, I was not patient enough, sorry about that and thank you for your help!
