### ISSUE TITLE
Problem when installing version 4.2 via helm

### ISSUE THREAD

**Issue by ZloyShadow** [stackrox/stackrox#7905]
Greetings.
When I'm trying to install StackRox 4.2.0 via helm chart or just via .sh quick-helm-install on RKE Rancher Kubernetes this is next error:
`Error: INSTALLATION FAILED: template: stackrox-central-services/templates/NOTES.txt:1:10: executing "stackrox-central-services/templates/NOTES.txt" at <include "srox.init" .>: error calling include: template: stackrox-central-services/templates/_init.tpl:243:3: executing "srox.init" at <include "srox.centralSetup" $>: error calling include: template: stackrox-central-services/templates/_central_setup.tpl:113:3: executing "srox.centralSetup" at <include "srox.configureCentralEndpoints" $._rox.central>: error calling include: template: stackrox-central-services/templates/_central_endpoints.tpl:51:38: executing "srox.configureCentralEndpoints" at <$central.monitoring.openshift>: nil pointer evaluating interface {}.openshift`
What could be the reason of this error? If I'm understand right problem that is there is no some openshift connector?
Tnx.

**Comment by stehessel** [comment]
Hi @ZloyShadow ,
thanks for the report. Could you post the full Helm command (+ Helm version) you ran? Thanks.

**Comment by stehessel** [comment]
I believe we are running into https://stackoverflow.com/a/59796677. We will provide a fix for older Helm versions, but in the meantime you can work around this issue by updating to Helm >= 3.10.0.
