### ISSUE TITLE
Some Pod is Unhealthy with message Readiness probe failed: Get "https://172.27.5.216:8080/scanner/ping": dial tcp 172.27.5.216:8080: connect: connection refused

### ISSUE THREAD

**Issue by tsukiazuma** [stackrox/stackrox#8029]
Hello,

When I deloy StackRox v4.2.1 on K8S v1.26.1, but pods of StackRox can't not running.
I revice warning like with command kubectl describe pod -n stackrox scanner-5dc49585fd-l5g7d:
`Warning  Unhealthy  25s (x19 over 2m58s)  kubelet            Readiness probe failed: Get "https://172.27.5.216:8080/scanner/ping": dial tcp 172.27.5.216:8080: connect: connection refused`

Firstly, I think that miss configure CNI for namespace StackRox. So I config with command:
`kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml --namespace=kube-system`
But I only revice another warning.

Some other information:
I configue CNI for K8s with: `kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml`

And now how can I do to fix warning  connection refused, please help me!

**Comment by dcaravel** [comment]
@tsukiazuma 

Can you provide more details, is it just the scanner pods that are failing to start, is it also scanner-db pods? Are the other central pods running OK (central and central-db)? (perhaps share the output of `kubectl get pods -n stackrox`)

Scanner will not be ready until scanner-db is also ready and the initial vulnerability data is populated - which may take time.

For any pods that are failing to be ready, if you could share the describe's and logs that would help us assist.

**Comment by porridge** [comment]
Closing inactive issue.
Please reopen if you have an update @tsukiazuma
