### ISSUE TITLE
Can scanner-slim be used as a standalone scanner without the central scanner ?

### ISSUE THREAD

**Issue by Lapant** [stackrox/stackrox#8050]
Hi StackRox community,

Thank you for your great project !

I read the document and see that the installation of the scanner-slim is optional. But can I only use scanner-slim to scan internal registries without deploying the "central" scanner ?

Thank you !

**Comment by dcaravel** [comment]
Hi @Lapant, the "central" scanner is still required to match vulnerabilities to the components identified by scanner-slim. More details [here](https://docs.openshift.com/acs/4.2/operating/examine-images-for-vulnerabilities.html#enhancing-image-scanning-by-accessing-delegated-image-scanning_examine-images-for-vulnerabilities)

**Comment by Lapant** [comment]
Hi @dcaravel , thank you for the quick respond !

Shame on me for not having thoroughly read the documentation. 

To make sure I clearly understand the matter : let's say that I have 2 OCP clusters, as of my understanding, I can use the central scanner to perform both indexing and vuln. matching of images located in the same cluster as the central (using the Scanner <> Sensor interaction). **But** if I want to scan images located in my other OCP intern registries, I must use scanner-slim for the indexing, then the result will be sent to the central scanner (through the sensor) for performing the vuln. matching.

Am I seeing this right ?

Tanks again for your help :-)

**Comment by dcaravel** [comment]
If I'm understanding correctly, that seems accurate me.

**Comment by connorgorman** [comment]
Closing as the question was answered. @Lapant Feel free to re-open if you feel otherwise, thanks!
