### ISSUE TITLE
Disable PodSecurityPolicies with helm chart - ArgoCD

### ISSUE THREAD

**Issue by makemesteaks** [stackrox/stackrox#8328]
Hello everyone,
I am deploying stackrox-secured-cluster-services and I want to disable PSP.
**I am installing the helm chart, through argo. Kubernetes version is 1.28**
Is there a way to disable them without forking the Chart?
Thank you

**Comment by johannes94** [comment]
Hello @makemesteaks,

The helm chart is implemented in a way that auto detects wether a cluster still has the PSP API resource. See this [part](https://github.com/stackrox/stackrox/blob/7856a66afb2d3a167524c4597041c64683a06768/image/templates/helm/shared/templates/_psp.tpl#L10-L11).

If this is for some reason not working in your situation with Argo you can force this value to be false by setting it explicitly e. g. adding following to the helm call.

```
--set system.enablePodSecurityPolicies=false
```

Hope this helps you solve your issue :)

**Comment by makemesteaks** [comment]
Thank you for the answers,
@johannes94 can I pass that as a flag to the values as well such as in the example below?

```
system:
   enablePodSecurityPolicies: false
```

**Comment by johannes94** [comment]
Yes, that should work as well.
