### ISSUE TITLE
IRSA for stackrox integration with Amazon Security Hub

### ISSUE THREAD

**Issue by gecube** [stackrox/stackrox#8393]
Good day colleagues,

First of all I want to say thanks to every developer of Stackrox - it is really damn good security tool for any k8s cluster. And I am very happy to improve the number of Stackrox users all around the globe.

Secondly, I want to share my experience. So right now we are installing the Stackrox package on top of every cluster (central + agents). I abandoned to install a central on the separate cluster, because of regulation and it makes the configuration easier: I can make the different set of policies in every central and don't worry that I will disable more than necessary. Or otherwise.

Also we are hosting in Amazon. It has its own security system called "AWS Security Hub". It is nice and covers our basic needs. And also provides not very convenient but a single interface to view events and security issues so I decided to integrate Stackrox with it. Now I need to create a user inside of every Amazon account and assign it a proper permissions. And generate an access and secret keys. It means that in some time in future I will need to rotate them. 

Stackrox has its own integration with AWS Security Hub with a button.

<img width="302" alt="Screenshot 2023-10-27 at 15 29 07" src="https://github.com/stackrox/stackrox/assets/2912732/b4ccdeeb-ca0c-4262-a805-cd5c28e5e1e4">
<img width="1218" alt="Screenshot 2023-10-27 at 15 23 05" src="https://github.com/stackrox/stackrox/assets/2912732/dbe8bffd-df92-4f2a-85b7-8a18354aac90">
<img width="1013" alt="Screenshot 2023-10-27 at 15 23 09" src="https://github.com/stackrox/stackrox/assets/2912732/fa059863-6aaa-4fe8-b50d-73eb05b408d4">

Unfortunately, it does not look like very convenient. As a user of Stackrox and user of Amazon cloud I want to utilise so-called IRSA approach. When I will be able to prepare a specific Role in Amazon cloud with proper permissions, set on service account of stackrox a special annotation and voila! I won't need to explicitly enter the access and secret keys (which, of course, could be stolen)

I'd like to hear your ideas on this topic. Is it possible?

**Comment by gecube** [comment]
p.s. not sure what happened, but also it looks like that you have broken pipelines.
<img width="1158" alt="Screenshot 2023-10-27 at 15 44 48" src="https://github.com/stackrox/stackrox/assets/2912732/72695ef3-1643-4297-a0af-82c1ce8f33fd">

**Comment by lvalerom** [comment]
Maybe @stackrox/core-workflows can help with this?

**Comment by stehessel** [comment]
Hey @gecube,
I'm happy to report that we are working on increasing our STS support for integrations. The setting for AWS security hub will look similar to what we already have for our S3 integration (`Use container IAM role` toggle instead of static credentials).

**Comment by stehessel** [comment]
Closing as completed by https://github.com/stackrox/stackrox/pull/8826
