### ISSUE TITLE
stackrox: central crashes with the error "Action Mutex.Unlock took more than 5s to complete"

### ISSUE THREAD

**Issue by innokgoldberg** [stackrox/stackrox#8562]
Hello.

Kubernetes v1.23.7
kernel 4.18.0-425.3.1.el8.x86_64
central version 4.2.x-450-g8f44335388
installation & configuration  via helm chart

We occasionally get central pod CrashLoopBackOff with the following error:
```
Action Mutex.Unlock took more than 5s to complete. Stack trace:
github.com/stackrox/rox/pkg/sync.(*Mutex).Unlock (github.com/stackrox/rox/pkg/sync/mutex_dev.go:79)
github.com/stackrox/rox/pkg/concurrency.(*KeyedMutex).Unlock (github.com/stackrox/rox/pkg/concurrency/keyed_mutex.go:46)
github.com/stackrox/rox/central/node/datastore.(*datastoreImpl).UpsertNode (github.com/stackrox/rox/central/node/datastore/datastore_impl.go:207)
github.com/stackrox/rox/central/risk/manager.(*managerImpl).CalculateRiskAndUpsertNode (github.com/stackrox/rox/central/risk/manager/manager.go:189)
github.com/stackrox/rox/central/reprocessor.(*loopImpl).reprocessNode (github.com/stackrox/rox/central/reprocessor/reprocessor.go:429)
github.com/stackrox/rox/central/reprocessor.(*loopImpl).runReprocessingForObjects.func1 (github.com/stackrox/rox/central/reprocessor/reprocessor.go:279)
runtime.goexit (runtime/asm_amd64.s:1598)
SIGABRT: abort
PC=0x24b8061 m=0 sigcode=0

```
This error is temporary and vanishes after some unpredictable time (central worktime/downtime looks like 50%/50%), exists at different stackrox versions (it was at 4.1.x and in 4.2.x) and belongs to specific cluster (one master, several slave clusters) as other central instances (installed on outher master/slave k8s clusters) with the same k8s, kernel and stackrox versions are not affected. Downtime periods usually lasts several hours, then several hours central operations normally. Due to trace the error seems to be connected with the slave clusters and receiving data from them. 

How can we overcome the problem (ideally without removing stackrox slave clusters from central  ).

**Comment by connorgorman** [comment]
Hi @innokgoldberg, it looks like you're running a dev version of stackrox and not a release build, which is not recommended. This mutex timeout is a check for development builds that locks aren't being held for a long period of time. Until 4.3 is released, at which point I recommend you upgrade. You can disable this by setting the environment variable on the Central MUTEX_WATCHDOG_TIMEOUT_SECS=0

**Comment by connorgorman** [comment]
Hi @innokgoldberg I'm going to close this ticket as it seems to be related to run dev builds, which is not recommended and 4.3 has been released. Thanks!
