### ISSUE TITLE
cant connect from another cluster

### ISSUE THREAD

**Issue by Nello-Angelo** [stackrox/stackrox#8760]
[files.zip](https://github.com/stackrox/stackrox/files/13445226/files.zip)
[sensor-yandex-prod.zip](https://github.com/stackrox/stackrox/files/13445313/sensor-yandex-prod.zip)
[sensor-do-prod (1).zip](https://github.com/stackrox/stackrox/files/13445314/sensor-do-prod.1.zip)

from digital ocean

this is logs of control
```
No certificates found in /usr/local/share/ca-certificates
No certificates found in /etc/pki/injected-ca-trust
main: 2023/11/23 00:23:05.937779 main.go:39: Info: StackRox Sensor Admission Control Service, version 4.2.2
admission-control/alerts: 2023/11/23 00:23:05.991398 sender.go:50: Info: Starting admission control alert pusher
pkg/grpc: 2023/11/23 00:23:05.991716 server.go:256: Info: Launching backend gRPC listener
admission-control/settingswatch: 2023/11/23 00:23:05.992336 sensor_push.go:66: Warn: Communication to sensor failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup sensor.stackrox.svc on 10.245.0.10:53: no such host". Retrying in 8.378399811s
pkg/grpc: 2023/11/23 00:23:05.994411 server.go:425: Info: TLS-enabled HTTP server listening on [::]:8443
admission-control/settingswatch: 2023/11/23 00:23:14.371230 sensor_push.go:66: Warn: Communication to sensor failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup sensor.stackrox.svc on 10.245.0.10:53: no such host". Retrying in 13.494335104s
admission-control/settingswatch: 2023/11/23 00:23:27.866108 sensor_push.go:66: Warn: Communication to sensor failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup sensor.stackrox.svc on 10.245.0.10:53: no such host". Retrying in 12.483567249s
admission-control/settingswatch: 2023/11/23 00:23:40.352934 sensor_push.go:66: Warn: Communication to sensor failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: lookup sensor.stackrox.svc on 10.245.0.10:53: no such host". Retrying in 33.721809317s
admission-control/manager: 2023/11/23 00:24:14.086305 manager_impl.go:424: Info: Initial resource sync with Sensor complete
```

this logs of collector
```
Collector Version: 3.16.1
OS: Debian GNU/Linux 11 (bullseye)
Kernel Version: 5.18.0-0.deb11.4-amd64
Starting StackRox Collector...
[INFO    2023/11/23 00:23:20] Hostname: 'pool-bgsfpmhvp-yr9v1'
[INFO    2023/11/23 00:23:20] User configured collection-method=ebpf
[INFO    2023/11/23 00:23:20] Afterglow is enabled
[INFO    2023/11/23 00:23:20] CORE_BPF collection method is available. Check the documentation to compare features of available collection methods.
[INFO    2023/11/23 00:23:20] Sensor configured at address: sensor.stackrox.svc:443
[INFO    2023/11/23 00:23:20] Attempting to connect to Sensor
[INFO    2023/11/23 00:23:45] Successfully connected to Sensor.
[INFO    2023/11/23 00:23:45] Module version: 2.6.0
[INFO    2023/11/23 00:23:45] Config: collection_method:ebpf, useChiselCache:1, scrape_interval:30, turn_off_scrape:0, hostname:pool-bgsfpmhvp-yr9v1, processesListeningOnPorts:1, logLevel:INFO, set_import_users:0, collect_connection_status:1
[INFO    2023/11/23 00:23:45] Candidate drivers: 
[INFO    2023/11/23 00:23:45] collector-ebpf-5.18.0-0.deb11.4-amd64.o
[INFO    2023/11/23 00:23:45] Attempting to download collector-ebpf-5.18.0-0.deb11.4-amd64.o
[INFO    2023/11/23 00:23:45] Attempting to download kernel object from https://sensor.stackrox.svc:443/kernel-objects/2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz
[INFO    2023/11/23 00:23:45] HTTP Request failed with error code 404
[WARNING 2023/11/23 00:25:45] [Throttled] Unexpected HTTP request failure (HTTP 503)
```

this is logs of sensor
```
pkg/kocache: 2023/11/23 00:24:11.066320 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:11.066538 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:14.400198 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:14.400387 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:14.731837 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:14.731993 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:15.620764 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:15.620948 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:16.069232 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:16.069391 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:19.403058 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:19.403174 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:19.734545 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:19.734701 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:20.622326 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:20.622566 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:21.072026 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:21.072159 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:24.405556 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:24.405714 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:24.737081 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:24.737237 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:25.623841 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:25.624117 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:26.074678 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:26.074818 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:29.408494 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:29.408661 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:29.739543 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:29.739659 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:30.625524 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:30.625666 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
pkg/kocache: 2023/11/23 00:24:31.077481 source.go:58: Error: probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/11/23 00:24:31.077631 server_handler.go:119: Info: kernel probe 2.6.0/collector-ebpf-5.18.0-0.deb11.4-amd64.o.gz not found
```

![Screenshot_10](https://github.com/stackrox/stackrox/assets/82488489/0ca7e28f-70cc-4583-86c9-f8c589aead81)
![Screenshot_5](https://github.com/stackrox/stackrox/assets/82488489/bc8c261f-9a7a-4064-9df9-81b7626100c6)
![Screenshot_8](https://github.com/stackrox/stackrox/assets/82488489/fb82d342-d15e-40fa-9e0d-01b92e3c0d24)
![Screenshot_9](https://github.com/stackrox/stackrox/assets/82488489/e2deef01-f78f-4dc6-9ede-f1ff222b0116)
![Screenshot_11](https://github.com/stackrox/stackrox/assets/82488489/1ace23e3-38d5-49c4-9105-1a111026e0a7)

from yandex cloud kubernetes 

![Screenshot_15](https://github.com/stackrox/stackrox/assets/82488489/6d3aee7c-92cd-4ebf-9d49-e17dec3e1ecc)
![Screenshot_13](https://github.com/stackrox/stackrox/assets/82488489/a8076535-e397-46d8-89c3-a74e22a4ac23)
![Screenshot_14](https://github.com/stackrox/stackrox/assets/82488489/92f2dd18-78ee-4552-8787-cfdbf09de7ca)
![Screenshot_16](https://github.com/stackrox/stackrox/assets/82488489/b96a265a-f9de-481e-b212-8653eab30094)

**Comment by Nello-Angelo** [comment]
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackrox
  namespace: stackrox
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stackrox.timo.group
      secretName: stackrox-tls
  rules:
    - host: stackrox.timo.group
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: central
                port:
                  name: https
```

**Comment by Nello-Angelo** [comment]
i can show in discord my problems

**Comment by Nello-Angelo** [comment]
@stackrox/collector-team could you please have a look?

**Comment by Nello-Angelo** [comment]
@rukletsov @dvail please pay attention

**Comment by ovalenti** [comment]
Hello @Nello-Angelo,

communication from Sensor to Collector seems ok.

To be sure that I understand your query, you are having issues connecting a cluster to your central instance ?

What is the value of the envvar `ROX_CENTRAL_ENDPOINT` in you sensor deployment, please ?

**Comment by Nello-Angelo** [comment]
Admission Control Service can start

**Comment by ovalenti** [comment]
If `stackrox.timo.group` works as a URL to access Central's web interface; then you could create a test POD in your cluster to check that there is no specific networking rule preventing access to `stackrox.timo.group`

**Comment by ovalenti** [comment]
From the logs, Collector seems able to connect to Sensor by using the same service name. Are you sure that the POD with the failure is running on the same cluster as Sensor ?

Stackrox does not do anything special with the network; and the capability for PODs to communicate with each other is a K8S topic. Unless this is a NetworkPolicy...

I am afraid I cannot offer support over Discord, but I will do my best to solve your issue if I can understand what happens here.

**Comment by Nello-Angelo** [comment]
i have failed admission-control pods please help with it

**Comment by Nello-Angelo** [comment]
@ovalenti

**Comment by ovalenti** [comment]
Hello @Nello-Angelo, the fact that your compliance container cannot connect to sensor on `sensor.stackrox.svc` looks like a kubernetes issue. I suggest to check that sensor is running:
- on the same cluster
- in the stackrox namespace

Overall, the fact that your sentences are not longer than 5 words does not really help. Please, explain a bit more what your problem is, so that I can help.

**Comment by Nello-Angelo** [comment]
do you have good documentation to install agents on other clusters? give me the link if you have, i will try again

**Comment by ovalenti** [comment]
You are probably using helm charts ?

The documentation for installing the clustered-services in this case can be found at : https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_security_for_kubernetes/4.3/html/installing/installing-rhacs-on-other-platforms#configure-secured-cluster-services-helm-chart-customizations-other

But basically, admission-control is reaching to sensor via a Cluster service named sensor. So as long as Sensor is deployed in the `stackrox` namespace, and compliance+sensor are running on the same k8s cluster; they should be able to find each other. This is the very fundamental k8s networking environment.

**Comment by Nello-Angelo** [comment]
yes, but it’s normal to install stackrox with its components in the same cluster. The problem is to connect other clusters to the centralized stackrox in another cluster

**Comment by ovalenti** [comment]
You are right, the connection of a remote secured cluster to a central instance can be challenging. However, the `admission-control` and `sensor` deployments are always talking to each-other within the same cluster.

So, the `admission-control` issue seems unrelated to the fact that the cluster is remote.

For the remote-Sensor to Central connection issue, did you generate an helm chart init bundle ?

Also, you could try to deploy a co-located central+secured-cluster to verify that your workflow is correct. Or maybe you tried this already, did it work ?

**Comment by Nello-Angelo** [comment]
i have central cluster in cloud and i connect to a cluster free. Clusters are opened for free connection. No I files from this menu
![Screenshot_8](https://github.com/stackrox/stackrox/assets/82488489/e5348d20-9339-4d06-a2cf-4af76687ee6d)

**Comment by Nello-Angelo** [comment]
why i get this error ?
![Screenshot_8](https://github.com/stackrox/stackrox/assets/82488489/7cc3c75a-fd4e-4465-8dde-d8849b630ff3)

**Comment by Nello-Angelo** [comment]
i just dont understand why collector can connect to sensor but admission-control cant
![Screenshot_9](https://github.com/stackrox/stackrox/assets/82488489/d0719c63-19c0-464b-93ce-59fd40695745)
![Screenshot_8](https://github.com/stackrox/stackrox/assets/82488489/b1521c03-ac23-48a1-ae43-aa214d44805a)

**Comment by ovalenti** [comment]
I can't find any reason for that to fail. Moreover, the error mentions a service resolution issue.

The installation method in the documentation I sent above suggests to create an init bundle from Platform_Configuration->Integrations->Cluster_Init_Bundle and use this yaml file to customize the helm install. This is the workflow I use; there may be something broken with the InstallCluster zip file method ?

**Comment by Nello-Angelo** [comment]
check it please

**Comment by vikin91** [comment]
Inability to communicate with `sensor.stackrox.svc` with error `no such host` hints on a problem with kube DNS. I saw some screenshots showing sensor running in the correct namespace, so as long as sensor service is there (and it must be, because Collector connects to it), then all looks fine with the installation. I would suggest to investigate why kube DNS is unable to resolve the name (maybe look at the logs?)

**Comment by vikin91** [comment]
Could you maybe show the output of `kubectl -n stackrox get svc -o wide`?

**Comment by Nello-Angelo** [comment]
1) https://github.com/stackrox/contributions/blob/main/ingress/nginx/Readme.md
2) https://access.redhat.com/articles/5941511 
3) bundle https://docs.openshift.com/acs/4.3/installing/installing_other/init-bundle-other.html#portal-generate-init-bundle_init-bundle-other 
4) https://docs.openshift.com/acs/4.3/installing/installing_other/install-secured-cluster-other.html
