### ISSUE TITLE
The 'roxctl image check' command fails to validate when specifying a custom category

### ISSUE THREAD

**Issue by mysekai7** [stackrox/stackrox#8944]
Hello everyone，when I use roxctl to perform image check, I specify a custom policy category. The execution result tells me that did not match any policy categories. 
I used StackRox version 4.3 for policy and category validation. The custom category name is 'Test Cate,' and the custom policy is 'Fixable CVSS >= 7 (COPY).' When I use 'roxctl image check' without specifying a category, the check report can return the custom policy 'Fixable CVSS >= 7 (COPY).' However, when specifying the custom category 'Test Cate,' it does not work. What could be the reason for this? 

When I restart ‘central’, this issue can be resolved. 

Screenshots of relevant operations：

![image](https://github.com/stackrox/stackrox/assets/685148/66578d3d-be9c-4020-b910-1069c77fb5ef)
![image (1)](https://github.com/stackrox/stackrox/assets/685148/fb4cf10d-cf94-49e5-bef0-dd8264016fee)
![image (2)](https://github.com/stackrox/stackrox/assets/685148/ed6ec8e9-1c65-4b59-b43b-5399507da95f)
![image (3)](https://github.com/stackrox/stackrox/assets/685148/cbab434e-e96c-47f8-b295-08059d8766b0)
![image (4)](https://github.com/stackrox/stackrox/assets/685148/0126c5ab-1c03-4d35-ad49-6ca789573700)

**Comment by dhaus67** [comment]
Hey @mysekai7 , this one is addressed with https://github.com/stackrox/stackrox/commit/f604212280d0acf4e08cbd8800d7cf2d817adfb5 which will release with 4.4.0 soon™.

**Comment by porridge** [comment]
Fixed by https://github.com/stackrox/stackrox/pull/7864
