### ISSUE TITLE
How to choose and utilize the compliance management functionality of ACM/ACS ?

### ISSUE THREAD

**Issue by mysekai7** [stackrox/stackrox#9163]
Hello all, I am using both OCP ACM and ACS products concurrently, and I have noticed that both products offer cross-cluster compliance management features. This has left me somewhat puzzled about how to choose and utilize the compliance management functionality of ACM/ACS.

**Comment by srcporter** [comment]
For the Red Hat OpenShift application platform, you'll ultimately want to use all of these tools to meet hardening or compliance standards. OpenShift Compliance Operator provides the mechanisms for performing SCAP scanning and rule evaluation. ACS provides visibility and export for CO SCAP result data. In the case of hardening profiles (like CIS benchmarks for OCP) ACM can provide for automated remediation of identified rule violations, across multiple OCP clusters, or, better yet, provisioning of new clusters with hardened settings. For "workload" misconfiguration, ACS Policies can guide developers and SREs towards Kubernetes configuration that can meet these standards.

**Comment by srcporter** [comment]
Further information on compliance features in ACS are part of the public roadmap presentation: https://www.youtube.com/watch?v=vD0rsWco0VY
