### ISSUE TITLE
Stackrox helm chart PodSecurityPolicy deprecation/deletion in v1.21/v1.25

### ISSUE THREAD

**Issue by innokgoldberg** [stackrox/stackrox#9178]
Hello.

Do You have plans for stackrox helm chart PSP replacement for k8s clusters newer than v1.25 due to remove of this functional? If yes, what it will be (PSS/OPA) and what are the terms of PSP replacement  implementation?

Thank You.

**Comment by mclasmeier** [comment]
Hi!

Which StackRox version are you referring to? In recent versions of StackRox PSPs are only included for backwards compatibility and are not installed on newer Kubernetes versions (without any replacement).

Does this help?
Moritz

**Comment by mclasmeier** [comment]
Will close this due to lack of activity.
