### ISSUE TITLE
Jira Cloud Integration fails

### ISSUE THREAD

**Issue by mtcolman** [stackrox/stackrox#9451]
I've tried to connect to a project on Jira Cloud, but I get this error:
![image](https://github.com/stackrox/stackrox/assets/33348891/e79da62d-1a9c-4cf3-863a-bddf414ed544)

Using ACS v4.3.3.

If I `curl` the Jira Cloud endpoints myself, I can retrieve all the information ACS claims to be. Wondering if this is related to #8679 ? Do you know when ACS 4.3.4 will be released and will it have this fix contained within?

Thanks in advance.

**Comment by vikin91** [comment]
CC @kylape

**Comment by kylape** [comment]
Yes, #8679 fixes that problem.  I can't say for sure whether #8679 will be in 4.3.4, but it is currently targeted for 4.4.

**Comment by mtcolman** [comment]
Is there any workaround for this - otherwise I'm a bit stuck?

**Comment by kylape** [comment]
The only workaround is to use an unreleased version of StackRox.  Is that something you'd be willing to try out?

**Comment by mtcolman** [comment]
Yes potentially, I have a demo cluster I can use this on. Is it possible to install via a helm chart?

**Comment by mtcolman** [comment]
Brilliant, thanks. I used:
```
helm upgrade stackrox-central-services -n stackrox --install ./stackrox-central-services-400.3.3.tgz --reuse-values \
--set central.image.fullRef=quay.io/stackrox-io/main:latest
```

And I've been able to create the integraiton. I shall test if tickets are now creating.

**Comment by mtcolman** [comment]
I was able to generate some tickets - thanks very much @kylape
