### ISSUE TITLE
ACS cannot fetch metadata when using mirrors in a disconnected environment

### ISSUE THREAD

**Issue by mtcolman** [stackrox/stackrox#9469]
We are on ACS 4.3 and yet are encountering this issue described here:
![image](https://github.com/stackrox/stackrox/assets/33348891/ce803b8e-b0cd-4c2c-87ec-632d49d238e9)

Yet it says this is fixed in 4.2.

Can someone please help me with how to get metadata in a disconnected environment? Within OpenShift I can use an ImageContentSourcePolicy (ICSP) (soon to be replaced by ImageDigestMirrorSet (IDMS)) but I can't see any mention of equivalent functionality in ACS?

Thanks in advance.

**Comment by dcaravel** [comment]
Hi @mtcolman - thanks for the message - agreed the docs could be made more clear, we'll get that updated.

TL;DR; ACS supports ICSP, IDMS, etc. via the delegated scanning capability.

The [4.2 release notes](https://docs.openshift.com/acs/4.2/release_notes/42-release-notes.html#vulnerability-scanning-support-for-registry-mirrors-in-ocp_release-notes-42) mention the association between delegated scanning and support for ICSP, IDMS, etc.

Refer to the [these instructions](https://docs.openshift.com/acs/4.3/operating/examine-images-for-vulnerabilities.html#configuring-delegated-image-scanning_examine-images-for-vulnerabilities) for how to enable delegated scanning. 

Hope this helps.

**Comment by mtcolman** [comment]
Thanks @dcaravel, much appreciated. Yes the docs could definitely benefit from being clearer on this.
