### ISSUE TITLE
UI reports Vulnerability definitions as out of date, definitions manifest in Central is correct 

### ISSUE THREAD

**Issue by ccodreanu** [stackrox/stackrox#9747]
Hello,

We're running Stackrox 4.3.4 and the "Vulnerability definitions" in the UI under Platform Configuration > System Health are reported as out of date.

We've had some CVEs reported in Stackrox that have been released this year and the UI reports the vulnerabilities as released in Oct 2023.

Checking in the security definitions directory under /tmp in Central, the manifest file reports:
```
{"since":"2023-10-25T15:11:31.926496239Z","until":"2024-01-30T12:10:19.047332054Z"}
```

so I believe the UI is wrongly reporting these definitions as out of date.

Removing the definitions, restarting Central, does not help.

Thank you!

**Comment by SimonBaeumer** [comment]
Hi @ccodreanu ,
thank you for reporting this issue.
@stackrox/ui can you take a look at this issue? It looks like the backend data is correct.

**Comment by vjwilson** [comment]
@ccodreanu The UI is fully rendered in the client browser, based on JSON data returned by API calls.

Please open your browser's dev tools and then refresh the page. Then, look in the Network pane of the browser's dev tools for a Fetch/XHR call that ends in 
`/v1/integrationhealth/vulndefinitions?component=SCANNER`

and see if the date it returns is the date you found on the server.

(The UI code simply checks if the date it gets is within 24 hours of the current datetime, to determine whether to say it's up-to-date or not.)

**Comment by ccodreanu** [comment]
hey @vjwilson, stackrox for me does a call to `/v1/integrationhealth/vulndefinitions` and gets `{"lastUpdatedTimestamp":"2023-07-18T23:04:49.653716317Z"}` in response now this is maintained across restarts (also made sure to remove the vuln definitions although they are in /tmp)

**Comment by danekantner** [comment]
I've definitely had the version date _revert_ (back to what seemingly was probably the date the image itself was created) after a pod restart after this newest install. This does seem like different/new behavior from past revisions. Though in my case it generally does correct itself pretty shortly.

**Comment by dcaravel** [comment]
Howdy!

> I've definitely had the version date revert (back to what seemingly was probably the date the image itself was created) after a pod restart. This does seem like different/new behavior from past revisions before 4.3.x (I am on 4.3.4). Though in my case it generally does correct itself pretty shortly.

@danekantner - your observation is right on point - the "Stackrox Scanner" doesn't maintain state between restarts, on fresh restart the date will be close to when the image was created and be updated shortly thereafter when the latest definitions are done loading.

> Checking in the security definitions directory under /tmp in Central, the manifest file reports:

@ccodreanu - the vuln definitions date show in the UI ultimatly comes from one of the scanner pods (via an API request sent by central), although central may have downloaded the updated file you're seeing in `/tmp`, it's possible something is preventing scanner from loading the file.

Take a look at the scanner pods and ensure they are running and healthy, also look at the scanner logs for any indication the update has failed, some messages to look for:
- `removing diff dump output path`
- `fetching update from URL`
- `updating from vuln dump`

These messages if found will be followed by an error with more details as to why the error occured.  If that doesn't help consider restarting the scanner and scanner-db pods and seeing if the issue persists.

Hope this helps.

**Comment by ccodreanu** [comment]
thanks @dcaravel . I did notice `updating from vuln dump` in our error logs with

```
updating from vuln dump: error beginning vuln loading: determining whether to update: cannot update with manifest: its start time (2024-02-28 00:20:53+0000 UTC) is after the DB update time (2023-07-18 23:04:49+0000 UTC)
```

a couple of restarts of both scanner and scanner-db did the trick and the UI is now updated.

Isn't the message misleading? Shouldn't a more recent manifest be used to update the db?

**Comment by dcaravel** [comment]
Great! 

> Isn't the message misleading? Shouldn't a more recent manifest be used to update the db?

That error is indeed a bit cryptic.  Each vuln diff has a `manifest.json` which looks similar to:

```json
{
    "since": "2024-02-28T00:20:53.211664833Z",
    "until": "2024-04-18T18:08:08.56807675Z"
}
```
This diff contains all the vulnerabilities that have been updated since a particular date.  This `since` date logically should be at or before the date in the database (which represents the last time vulnerabilities were loaded successfully (`DB update time`)).  

The intent of the error, I believe, is a safety check to prevent loading a diff that would be missing updated vulns.

**Comment by dcaravel** [comment]
Hi @ccodreanu, closing this issue since it seems things are working now. Feel free to comment if you have additional questions. Thanks!
